### ISSUE TITLE
Error saving config file in Wazuh plugin in Kibana 

### ISSUE THREAD

**Issue by Akikazuu** [wazuh/wazuh-kibana-app#3499] opened 2021-07-23 09:21 UTC
| Wazuh | Elastic | Rev |
| ----- | ------- | ---- |
| 4.1.5 | 7.10.2 |  4107 |

**Description**
When i want to save a config file in the Wazuh plugin on Kibana, i got an error.

**Steps to reproduce**
On Wazuh plugin in Kibana.
Go to a config file like "local_rules.xml"
Modify the file then click on button "Save"

**Screenshots**
![image](https://user-images.githubusercontent.com/15688823/126761606-4b4e19e2-d2d3-48ea-ae4e-9a60c80655df.png)

Do not hesitate to request me for more informations.

**Comment by frankeros** [comment] 2021-07-26 19:14
Hello @Akikazuu, thanks for using Wazuh

In order to be able to help you, can you share the content of the rule? Please obfuscate any sensible data.
Are you using some Security plugin with Kibana? What version of Kibana are you using?
If you try to create a new rule, is the error occurring too?

Thanks in advance

**Comment by Akikazuu** [comment] 2021-07-27 07:30
Hello,

Kibana version is 7.10.2, there is no security plugin on Kibana, only Wazuh plugin.

The rule file, is a local_file.xml is syntaxically good (check with XML validator program + Wazuh plugin : no error), there is no problem when i update the file directly on the server.

The rule file is about 2k2 lines and full sensible data, i can't share it :/ 

There is the same error when i try to create a new rule file : 
![image](https://user-images.githubusercontent.com/15688823/127113356-41dc2034-95cb-4b93-adcf-910140631ba8.png)

Thanks for your support.

**Comment by frankeros** [comment] 2021-07-27 12:40
can you check these files on your manager host in order to find some error log regarding this issue?
`/var/ossec/logs/ossec.log`
`/var/ossec/logs/api.log`
`/var/ossec/logs/active-responses.log`

for example 
`grep -E "ERR|WARN" /var/ossec/logs/ossec.log`

> There is the same error when i try to create a new rule file :

When you try to create the new rule is it with the same content? or even you are getting the error with a simple rule like
```xml
<group name="local,syslog,sshd,">

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <rule id="200001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

</group>
```

**Comment by Akikazuu** [comment] 2021-07-27 13:27
All result below for grep -E "ERR|WARN" /var/ossec/logs/X.log command : 

ossec.log (only Invalid agent name):

2021/07/27 15:24:26 ossec-authd: ERROR: Invalid agent name xxxxxxxxxx (duplicated)
2021/07/27 15:24:26 ossec-authd: ERROR: Invalid agent name xxxxxxxxxx (duplicated)
2021/07/27 15:24:28 ossec-authd: ERROR: Invalid agent name xxxxxxxxxx (duplicated)
2021/07/27 15:24:29 ossec-authd: ERROR: Invalid agent name xxxxxxxxxx (duplicated)

api.log
2021/07/27 09:21:06 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
2021/07/27 09:25:06 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
2021/07/27 09:40:01 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
2021/07/27 15:20:40 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused

active-responses.log : File is empty
 
Same error when creating new rule : 
![image](https://user-images.githubusercontent.com/15688823/127161117-f4dbad55-0693-4178-be12-8dffca4aeec7.png)

**Comment by frankeros** [comment] 2021-07-27 15:37
Thanks for sharing these logs, maybe there is more information that could help us to determine what is happening. 
Can share your entire `ossect.log` and `api.log`, please?

**Comment by Akikazuu** [comment] 2021-07-28 07:29
Hello,

I activate debug options on api logs for more information about the error. 

Below the api.log when i try to add a rule file in the Wazuh plugin : 

> 2021/07/28 09:17:32 DEBUG: Receiving request "PUT /rules/files/test.xml" with parameters {'overwrite': 'false'}
2021/07/28 09:17:32 DEBUG: Decoded token {'username': 'wazuh-wui', 'roles': [1], 'token_nbf_time': 1627456613, 'run_as': False}
2021/07/28 09:17:32 INFO: wazuh-wui 172.22.XX.XX "PUT /rules/files/test.xml" done in 0.047s: 200
2021/07/28 09:17:32 DEBUG: Receiving request "GET /cluster/status" with parameters {} and body {}
2021/07/28 09:17:32 DEBUG: Decoded token {'username': 'wazuh-wui', 'roles': [1], 'token_nbf_time': 1627456613, 'run_as': False}
2021/07/28 09:17:32 INFO: wazuh-wui 172.22.199.115 "GET /cluster/status" done in 0.049s: 200
2021/07/28 09:17:32 DEBUG: Receiving request "GET /manager/configuration/validation" with parameters {} and body {}
2021/07/28 09:17:32 DEBUG: Decoded token {'username': 'wazuh-wui', 'roles': [1], 'token_nbf_time': 1627456613, 'run_as': False}
2021/07/28 09:17:32 ERROR: Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
Traceback (most recent call last):
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/manager.py", line 144, in validate_ossec_conf
    execq_socket.connect(execq_socket_path)
ConnectionRefusedError: [Errno 111] Connection refused

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/OPT/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 491, in wait_for
    return fut.result()
  File "/OPT/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/rbac/decorators.py", line 406, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/manager.py", line 197, in validation
    response = validate_ossec_conf()
  File "/OPT/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/manager.py", line 147, in validate_ossec_conf
    raise WazuhInternalError(1013, extra_message=extra_msg)
wazuh.core.exception.WazuhInternalError: Error 1013 - Unable to connect with socket: Socket: WAZUH_PATH/queue/alerts/execq. Error Connection refused
2021/07/28 09:17:32 INFO: wazuh-wui 172.22.XX.XX "GET /manager/configuration/validation" done in 0.051s: 500
2021/07/28 09:17:32 DEBUG: Receiving request "GET /security/user/authenticate" with parameters {}
2021/07/28 09:17:33 INFO: wazuh-wui 172.22.XX.XX "GET /security/user/authenticate" done in 0.176s: 200

For the ossec.log their is no more log than "Received request for a new agent" or "Invalid agent name".

**Comment by frankeros** [comment] 2021-07-28 15:35
Hi @Akikazuu, thanks for sending the info, 
It seems to be related with an [issue](https://github.com/wazuh/wazuh/issues/7968) solved in 4.2.0 version, 
in order to check if the problem that you reported is caused by the same issue, can you share the configuration of your **Active response**, please? 
You can get this info from the UI, on the page `Wazuh / Management / Configuration` under the section `System threats and incident response / Active response`, you'll find all the active responses config by pressing the `XML ` viewer as in the screenshot
![image](https://user-images.githubusercontent.com/26828184/127350429-2a85fcde-a088-4f13-899d-bfc7af361c1f.png)

In case your Active responses match with these [scenarios](https://github.com/wazuh/wazuh/issues/7968#issuecomment-817861214) when the issue occurs: 
- All Active responses are disabled
- The first Active response is disabled 

please try to enable all of them (temporally if you considered it) by editing the configuration in the same section `Wazuh / Management / Configuration`. Then save it and restart the manager, then try to create a new rule.
![image](https://user-images.githubusercontent.com/26828184/127351640-dff4cbef-58dd-4511-8c62-ba86657fe1f0.png)

Thanks in advance

**Comment by Akikazuu** [comment] 2021-07-29 09:02
Hello,

Their is problem i think, i cant fetch the both file : 

![image](https://user-images.githubusercontent.com/15688823/127463914-2bad6d8a-f15f-4347-9c26-f75d560e0b3e.png)

![image](https://user-images.githubusercontent.com/15688823/127463830-67320183-2e2e-4d89-8945-4f87d31b5378.png)

**Comment by frankeros** [comment] 2021-07-29 13:11
Hello, I think this is related too to the same issue. 

You can change the configuration of your manager directly from the config file in the host 
`/var/ossec/etc/ossec.conf`

check the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html), and the section of [active-response](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html) 
you should try to set enabled at least the first active-response block or all of them 
`<disabled>no<disabled>` 

After saving the config file restart the wazuh manager with 
-for Systemd:  `systemctl restart wazuh-manager`
-for SysV Init: `service wazuh-manager restart`

> I think it's because Wazuh is installed as "All-in-one deployment", not in "Distributed"
It should work in both cases

**Comment by Akikazuu** [comment] 2021-07-29 14:55
Hello,

Actually, we have not active-response enabled.

So i try to create an "fictive" active response like this : 
`<command>
    <name>host-deny</name>
    <executable>host-deny.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>

<active-response>
  <disabled>no</disabled>
  <command>host-deny</command>

  <location>defined-agent</location>
  <agent_id>032</agent_id>
  <level>10</level>
  <rules_group>sshd,|pci_dss_11.4,</rules_group>
  <timeout>1</timeout>
</active-response>`

After restarting the manager i was able to create or modify rules then save them. I hope that will not affect our actual configuration -> can you confirm ? 

I hope this workaround is fixed for the next version of Wazuh.

Thank you very much for your support, your availability and your speed.

Stay safe and have a good day.

**Comment by frankeros** [comment] 2021-07-30 14:41
Hello, you are welcome!! 

> After restarting the manager i was able to create or modify rules then save them. I hope that will not affect our actual configuration -> can you confirm ?

If the "fictive" active-response is no triggering, it shouldn't affect the configuration.
Just in case you can check [here](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/how-it-works.html#when-is-an-active-response-triggered) how active-response works.

I'm closing this issue. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

Best!

**Closed by frankeros** 2021-07-30 14:41 UTC
Labels: bug, community
