### ISSUE TITLE
How to integrate fortigate logs with Wazuh?

### ISSUE THREAD

**Issue by nkhljswl** [wazuh/wazuh-kibana-app#2152] opened 2020-03-25 07:45 UTC
Hi Folks,

I have recently deployed Wazuh in our infrastructure. It was pretty easy to integrate Windows and Linux os for monitoring. So here is the problem- 

I followed Wazuh documentation to configure network devices to receive logs in Wazuh manager.Also allowed the port and ip in ossec.conf. I can see the syslog traffic coming from source machine in tcpdump but events are not visible in Wazuh UI. 

Also if you can help me to understand below queries:

1. Where syslog events are getting stored?
2. How decoders identify the log path of fortigate

Wazuh Version: 3.11

Any help would be appreciated.

**Comment by jsanchez91** [comment] 2020-03-25 09:58
Hi @nkhljswl,
The alerts generated by Wazuh are stored in `/var/ossec/logs/alerts/alerts.(json|log)` and the events at `/var/ossec/logs/archives/archives.(json|log)`.
Note: By default the event storage is disabled, to enable it change in ossec.conf this:
```xml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall> <!-- This -->
    <logall_json>yes</logall_json> <!-- This -->
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
  </global>
```
You can get more info about the archival data storage here. [archival-data-storage](https://documentation.wazuh.com/3.12/getting-started/architecture.html#archival-data-storage)
After made the change you can check if your environment generate Syslog events in the files  `/var/ossec/logs/archives/archives.(json|log)`. 

If you have events but no alerts, you may need to create decoders or custom rules, this Issue can help. https://github.com/wazuh/wazuh-kibana-app/issues/1884

You can also check this blog: [Monitoring network devices Wazuh hids](https://wazuh.com/blog/monitoring-network-devices-wazuh-hids/)

I hope this helps you, don't hesitate to ask if you have any more questions.
Regards,
Jose.

**Comment by nkhljswl** [comment] 2020-03-29 05:53
Hi @jsanchez91 ,

I have updated the configuration. Also i have added fortigate decoder. [Link](https://github.com/wazuh/wazuh-kibana-app/issues/1884#issuecomment-553386278)

But, still there couldn't find logs in archive.log .

**Comment by jsanchez91** [comment] 2020-04-01 07:13
Could you explain the steps you take to set up Fortigate on Wazuh?

**Comment by nkhljswl** [comment] 2020-04-01 13:12
Sure,

Step 1 Enabled syslog in Fortigate firewall to forward log.
Step 2 Added remote port 514 in ossec.conf
Step 3 Updated configuration as per your recommendation
Step 4 Created a xml file inside etc/decoder/custom_fortigate_decoder.xml [File](https://github.com/wazuh/wazuh-kibana-app/issues/1884#issuecomment-553386278)
Step 5 Restarted Wazuh manager

**Comment by jsanchez91** [comment] 2020-04-03 07:29
Hello,

We can check a few things.

The first is the "var/ossec/logs/ossec.log" file. Check if you have any errors about the `rsyslog`.

If you have no errors, make sure your remote configuration is good, check if the IP of the Fortigate machine is in the `allowed-ips` and the `local_ip` are visible by the Fortigate.

And finally, check the configuration in the file `/etc/rsyslog.conf` in the Fortigate side. Try to add this to forward all logs to Wazuh:

```bash
*.* @[WAZUH-MANAGER-IP]:514
```

In these links you can get more info about `rsyslog`:
[How to configure Rsyslog client to send events to Wazuh](https://wazuh.com/blog/how-to-configure-rsyslog-client-to-send-events-to-wazuh/)
[Remote documentation](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/remote.html#allowed-ips)

If you have any questions, don't hesitate to ask.
Regards,
Jose

**Comment by nkhljswl** [comment] 2020-04-06 09:32
Hi @jsanchez91 

The first is the "var/ossec/logs/ossec.log" file. Check if you have any errors about the rsyslog

**I can't see any error message related to rsyslog.**

If you have no errors, make sure your remote configuration is good, check if the IP of the Fortigate machine is in the allowed-ips and the local_ip are visible by the Fortigate.

**Please find the below screenshot of my configuration**

![image](https://user-images.githubusercontent.com/29570856/78468205-88743080-7726-11ea-8b21-355d8a4a7f0a.png)

And finally, check the configuration in the file /etc/rsyslog.conf in the Fortigate side. Try to add this to forward all logs to Wazuh:

**I can see the syslog traffic in tcpdump**

**Comment by jsanchez91** [comment] 2020-04-07 07:22
After adding the settings to rsyslog.conf to forward all logs, do you receive any events or alerts?
Run this command to see if you get any events:

```
tail -n 1000 /var/ossec/logs/archives/archives.json  | grep "<your-fortigate-ip>"
```

**Comment by nkhljswl** [comment] 2020-04-07 11:07
Hi Jose,

I can see only archives.log. I couldn't find archives.json.

**Comment by jsanchez91** [comment] 2020-04-08 07:00
To save the events in the files.json file enable the logall_json option in the ossec.conf.

```xml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json> <!-- THIS OPTION -->
    <email_notification>no</email_notification>
    <smtp_server>smtp.example.wazuh.com</smtp_server>
    <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
  </global>
...
```
After the change, restart Wazuh.

**Comment by nkhljswl** [comment] 2020-04-08 07:30
Hi Jose,

Configuration is already in place.

![image](https://user-images.githubusercontent.com/29570856/78756731-53691780-798c-11ea-9e43-b0c7243b504f.png)

**Comment by nkhljswl** [comment] 2020-04-12 11:18
Is there any other workaround to get firewall logs in Wazuh?

**Comment by jsanchez91** [comment] 2020-04-13 06:54
Hi @nkhljswl,

It's strange that you don't have the `archives.json` file with the logall_json option enabled.

Could you share your `ossec.log` with me to see if your environment has any problems?

**Comment by nkhljswl** [comment] 2020-04-13 11:53
Hi Jose,


[ossec.log](https://github.com/wazuh/wazuh-kibana-app/files/4469374/ossec.log)

**Comment by jsanchez91** [comment] 2020-04-14 07:07
Hello @nkhljswl,

I found no mistake, but it seems your Wazuh service has stopped.
```log
2020/04/08 13:43:41 ossec-authd: INFO: Exiting...
```

Share with me the output from running this command
```bash
systemctl status wazuh-manager
```
If the service has stopped, restart with this command.
```bash
systemctl start wazuh-manager
```

**Comment by jsanchez91** [comment] 2020-05-21 06:21
Hi @nkhljswl 

I am closing this issue due to inactivity. Please, if you still have this problem, feel free to open a new issue.

Thank you.

**Comment by hansaliyad1** [comment] 2020-11-04 21:19
@jsanchez91  I am having a similar problem as described by @nkhljswl  . I have followed all your instructions. I can also see archives.log/json and logs in them. I am not able to on Kibana. I have configured the decoder and rules as described in #1884  . I am not sure where I am getting wrong. I will appreciate any help!

**Comment by jsanchez91** [comment] 2020-11-10 10:36
Hi @hansaliyad1,

Could you share your archives.json with me?
I need to see if you have any events related to Fortigate

**Comment by hansaliyad1** [comment] 2020-11-10 13:43
Hey! @jsanchez91 

I am sorry! I won't be able to share that file since it contains sensitive information. Also, it is a really big file since it is running for a while now. But I can confirm it has all the events related to Fortigate.

**Comment by jsanchez91** [comment] 2020-11-11 16:43
Could you send me some examples of events related to Fortigate that hide sensitive information?

**Comment by jsanchez91** [comment] 2020-11-11 16:51
On the other hand, you have commented that you added the decoders and ruleset mentioned in this Issue: https://github.com/wazuh/wazuh-kibana-app/issues/1884

In this [comment](https://github.com/wazuh/wazuh-kibana-app/issues/1884#issuecomment-553386278), a rule is added that level 0, which by default does not generate alerts.

You can try to use the decoders and ruleset indicated in this other comment: https://github.com/wazuh/wazuh-kibana-app/issues/1884#issuecomment-557104742

**Comment by hansaliyad1** [comment] 2020-11-12 12:41
@jsanchez91 Thanks for your response again. I apologize for the delayed response. I did change the level number to 4. I ended removing wazuh and installed ELK. I just needed a log manager. It works now like charm. Thank you again for your help.

**Comment by jsanchez91** [comment] 2020-11-12 15:59
I'm glad I could help you, if everything is resolved I'll close the Issue.

If you have any further questions, please do not hesitate to reopen the Issue or use our [slack channel](https://wazuh.com/community/join-us-on-slack/), our [Google group](https://groups.google.com/forum/#!forum/wazuh)

Regards

**Closed by jsanchez91** 2020-11-12 15:59 UTC
Labels: community

**Comment by theazlan89** [comment] 2021-09-10 09:43
Hi,

May i know which format i should choose in Fortigate ?

default    Syslog format.
csv        CSV (Comma Separated Values) format.
cef        CEF (Common Event Format) format.

**Comment by syafeera92** [comment] 2022-06-16 05:23
Hi,

I can see the log in tail -n 1000 /var/ossec/logs/archives/archives.json but why i still cannot view fortigate log in wazuh discovery?

Thanks
