### ISSUE TITLE
Wazuh Dashboard UI Issue while extending the graphs

### ISSUE THREAD

**Issue by khembhatta0777** [wazuh/wazuh-kibana-app#3483] opened 2021-07-15 12:03 UTC
| Wazuh | Elastic |
| ----- | ------- | 
| 4.x   | 7.x     |

**Description**
There is a design issue that we can observer while extending the graphs inside wazuh plugins section. 

**Steps to reproduce**

1. Go to 'http;//localhost:5601'
2. Click on 'wazuh plugin in the left side nav'
3. Click any modules where you can see any graphs.
4. Extend the graphs and scroll you can see the search tab of the kibana overlapped the graphs and the graphs cant be terminated because of that. 

**Screenshots**
![wazuh-dashboard-1](https://user-images.githubusercontent.com/23493185/125785249-314bc8ee-a486-4880-a847-d8741e1bb4a0.PNG)

![kib](https://user-images.githubusercontent.com/23493185/125784744-346e8abb-dbf4-455d-b0aa-c474c52640ef.PNG)

**Additional context**

## System Detail

OS: Debian 10 (buster) RAM: 8gb CPU: 4

### general version info of applications
Browser: Brave, Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (64-bit)
wazuh: wazuh/wazuh-odfe:4.0.4_1.11.0 
kibana: wazuh/wazuh-kibana-odfe:4.0.4_1.11.0

**Comment by frankeros** [comment] 2021-07-15 12:58
Hello @khembhatta0777, thanks for reporting the issue. 

We already fixed a similar [issue](https://github.com/wazuh/wazuh-kibana-app/issues/2667) for v4.0.4 revision 4016 can you share what revision of the Wazuh app are you using, please? you can find it in the app  `Wazuh menu / Settings / About`
![image](https://user-images.githubusercontent.com/26828184/125791090-aa43d43f-85c5-4634-9017-78ca2f4007ed.png)

If you have the revision 4016 already installed, and your version was recently updated, you could try to clear the cache of your browser. 
Please follow [these steps](https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#conflict-with-the-wazuh-app-version-error-is-displayed) to do it.

**Comment by khembhatta0777** [comment] 2021-07-15 13:41
Hi @Franco Charriol thank you for reaching out. Yes you are right the
version that i am using is 4.0.4 and the app revision version is 4015, will
be looking at the latest revision.
Once again thank you for responding.

**Comment by frankeros** [comment] 2021-07-15 15:29
You are welcome, please let me know if the issue is fixed after the upgrade. Tks

**Comment by frankeros** [comment] 2021-08-17 11:58
I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Closed by frankeros** 2021-08-17 11:58 UTC
Labels: bug, community
