### ISSUE TITLE
Wazuh App not showing packages details in FreeBSD agent

### ISSUE THREAD

**Issue by dami-nicastro** [wazuh/wazuh-kibana-app#3586] opened 2021-08-25 16:06 UTC
### Packages details are not shown for FreeBSD agent in Wazuh App

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| **4.1.5** | **Wazuh App** | **Agent** | **Packages** | **FreeBSD 12.2 amd64** |

Hello team!
I have made an installation of a Wazuh agent in FreeBSD 12.2 amd64 and I have found that some information retrieved by Syscollector is not properly shown in Kibana web UI.

The documentation of Wazuh 4.1.5 shows that syscollector is capable to retrieve packages information from a FreeBSD machine:

https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#compatibility-matrix

However, the Kibana web UI only shows the amount of installed of packages but no packages are listed as we can see below:

![image](https://user-images.githubusercontent.com/86075186/130821908-0a32baee-45e7-43bc-b499-6ad9e83c19ef.png)

I have executed the corresponding API call and the result is correct:

![image](https://user-images.githubusercontent.com/86075186/130822302-e02bb56b-3cfe-4692-96c2-10cf7615e901.png)

Checking the **/var/ossec/logs/api.log**, we can see that the GET method executed when I click on "Inventory data" is also correct:

```
2021/08/24 09:30:56 INFO: wazuh-wui 192.168.19.128 "GET /syscollector/025/packages" with parameters {"limit": "10", "offset": "0"} and body {} done in 2.829s: 200
```
Putting the /var/ossec/logs/ossec.log in debug mode (wazuh_modules.debug=2), I also observed that packages are correctly retrieved. In this example, I have installed the package "gmake" and this was correctly monitored by syscollector:

```
root@freebsd:~ # less /var/ossec/logs/ossec.log | grep gmake
2021/08/24 19:09:57 wazuh-modulesd:syscollector[3010] syscollector_bsd.c:737 at sys_packages_bsd(): DEBUG: sys_packages_bsd() sending '{"type":"program","ID":1632587127,"timestamp":"2021/08/24 19:09:57","program":{"format":"pkg","name":"gmake","vendor":"tijl@FreeBSD.org","version":"4.3_2","architecture":"FreeBSD:12:amd64","description":"GNU version of 'make' utility"}}'
```
The only issue seems to be in Wazuh plugin for Kibana Web UI because the packages are not shown in the "Inventory data" details of the FreeBSD agent.
Please, let me know if you have further questions.

Thanks in advance for your help.

Damian

**Comment by jnasselle** [comment] 2021-09-22 12:09
Hi @wazuh/frontend,

I was working in #10126 when i were able to reproduce it. The root cause of this is related to this code snippet

https://github.com/wazuh/wazuh-kibana-app/blob/5f8abafa992a25ae6047343ee1510b6877d80001/public/components/agents/syscollector/inventory.tsx#L48-L54

As @dami-nicastro said, API is returning OK packages information, but App is using global.db information (os_uname, platform) to arrange certain columns, and FreeBSD was not including in this checks.

To validate this
- Sync FreeBSD agent with the Manager
- Stop both agent and manager
- Update `os_uname` in `agent` and change it to `Linux`
`sqlite3 global.db "UPDATE agent SET os_uname = 'Linux' where id = 002"`
- Start manager and look agent's inventory in Kibana App

![Screenshot from 2021-09-22 09-00-11](https://user-images.githubusercontent.com/1791430/134339769-367dad0f-7d4c-477e-a9bf-7aedf3b4cf59.png)

### Sample API request
<details>
  <summary>GET /syscollector/002/packages</summary>

```

{
  "data": {
    "affected_items": [
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:09Z"
        },
        "vendor": "garga@FreeBSD.org",
        "name": "cvsps",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "2.1_2",
        "size": 0,
        "description": "Create patchset information from CVS",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:09Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "curl",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "7.78.0",
        "size": 0,
        "description": "Command line tool and library for transferring data with URLs",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:09Z"
        },
        "vendor": "kde@FreeBSD.org",
        "name": "cmake",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.21.0",
        "size": 0,
        "description": "Cross-platform Makefile generator",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:09Z"
        },
        "vendor": "skrah@bytereef.org",
        "name": "mpdecimal",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "2.5.1",
        "size": 0,
        "description": "C/C++ arbitrary precision decimal floating point libraries",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:09Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "gettext-runtime",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.21",
        "size": 0,
        "description": "GNU gettext runtime libraries and programs",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "automake",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.16.3",
        "size": 0,
        "description": "GNU Standards-compliant Makefile generator",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "krion@FreeBSD.org",
        "name": "pcre2",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "10.37",
        "size": 0,
        "description": "Perl Compatible Regular Expressions library, version 2",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "desktop@FreeBSD.org",
        "name": "expat",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "2.4.1",
        "size": 0,
        "description": "XML 1.0 parser written in C",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-GSSAPI",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.28_1",
        "size": 0,
        "description": "Perl extension providing access to the GSSAPIv2 library",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "cperciva@FreeBSD.org",
        "name": "firstboot-pkgs",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.6",
        "size": 0,
        "description": "Install packages when the system first boots",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "vbox@FreeBSD.org",
        "name": "virtualbox-ose-additions-nox11",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "6.1.26_1",
        "size": 0,
        "description": "VirtualBox additions for FreeBSD guests",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-LWP-MediaTypes",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "6.04",
        "size": 0,
        "description": "Guess media type for a file or a URL",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "desktop@FreeBSD.org",
        "name": "libiconv",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.16",
        "size": 0,
        "description": "Character set conversion library",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "bhughes@FreeBSD.org",
        "name": "libuv",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.42.0",
        "size": 0,
        "description": "Multi-platform support library with a focus on asynchronous I/O",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:10Z"
        },
        "vendor": "ports-secteam@FreeBSD.org",
        "name": "ca_root_nss",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "3.69_1",
        "size": 0,
        "description": "Root certificate bundle from the Mozilla Project",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "garga@FreeBSD.org",
        "name": "git",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "2.32.0_1",
        "size": 0,
        "description": "Distributed source code management tool",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "zstd",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.5.0",
        "size": 0,
        "description": "Fast real-time compression algorithm",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "m4",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.4.19,1",
        "size": 0,
        "description": "GNU M4",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "readline",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "8.1.1",
        "size": 0,
        "description": "Library for editing command lines as they are typed",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "pkg@FreeBSD.org",
        "name": "pkg",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.17.1",
        "size": 0,
        "description": "Package manager",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "jmohacsi@bsd.hu",
        "name": "p5-IO-Socket-INET6",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "2.72_1",
        "size": 0,
        "description": "Perl module with object interface to AF_INET6 domain sockets",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-HTML-Parser",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.76",
        "size": 0,
        "description": "Perl5 module for parsing HTML documents",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "ume@FreeBSD.org",
        "name": "p5-Socket6",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.29",
        "size": 0,
        "description": "IPv6 related part of the C socket.h defines and structure manipulators",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:11Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-Error",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "0.17029",
        "size": 0,
        "description": "Error/exception handling in object-oriented programming style",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-Digest-HMAC",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.04",
        "size": 0,
        "description": "Perl5 interface to HMAC Message-Digest Algorithms",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "amdmi3@FreeBSD.org",
        "name": "p5-Encode-Locale",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.05",
        "size": 0,
        "description": "Determine the locale encoding",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-HTTP-Date",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "6.05",
        "size": 0,
        "description": "Conversion routines for the HTTP protocol date formats",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "libnghttp2",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.44.0",
        "size": 0,
        "description": "HTTP/2.0 C Library",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "danfe@FreeBSD.org",
        "name": "rhash",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.4.2",
        "size": 0,
        "description": "Utility and library for computing and checking of file hashes",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "autoconf",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "2.69_3",
        "size": 0,
        "description": "Automatically configure source code on many Un*x platforms",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "martin@waschbuesch.de",
        "name": "liblz4",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.9.3,1",
        "size": 0,
        "description": "LZ4 compression library, lossless and very fast",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-Authen-SASL",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "2.16_1",
        "size": 0,
        "description": "Perl5 module for SASL authentication",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "glewis@FreeBSD.org",
        "name": "libarchive",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.5.1,1",
        "size": 0,
        "description": "Library to create and read several streaming archive formats",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:12Z"
        },
        "vendor": "garga@FreeBSD.org",
        "name": "sudo",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.9.8p1",
        "size": 0,
        "description": "Allow others to run commands as root",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "rodrigo@FreeBSD.org",
        "name": "rsync",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.2.3_1",
        "size": 0,
        "description": "Network file distribution/synchronization utility",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "gmake",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "4.3_2",
        "size": 0,
        "description": "GNU version of 'make' utility",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-HTTP-Message",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "6.33",
        "size": 0,
        "description": "Representation of HTTP style messages",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "sbz@FreeBSD.org",
        "name": "libssh2",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.9.0_3,3",
        "size": 0,
        "description": "Library implementing the SSH2 protocol",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "zeising@FreeBSD.org",
        "name": "libffi",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.3_1",
        "size": 0,
        "description": "Foreign Function Interface",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-Net-SSLeay",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.90",
        "size": 0,
        "description": "Perl5 interface to SSL",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "svysh.fbsd@gmail.com",
        "name": "p5-IO-Socket-SSL",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "2.072",
        "size": 0,
        "description": "Perl5 interface to SSL sockets",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-HTML-Tagset",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "3.20_1",
        "size": 0,
        "description": "Some useful data table in parsing HTML",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:13Z"
        },
        "vendor": "svysh.fbsd@gmail.com",
        "name": "p5-Mozilla-CA",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "20200520",
        "size": 0,
        "description": "Perl extension for Mozilla CA cert bundle in PEM format",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "xxhash",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.8.0",
        "size": 0,
        "description": "Extremely fast non-cryptographic hash algorithm",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-Clone",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.45",
        "size": 0,
        "description": "Recursively copy Perl datatypes",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "mat@FreeBSD.org",
        "name": "perl5",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "5.32.1_1",
        "size": 0,
        "description": "Practical Extraction and Report Language",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "autoconf-wrapper",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "20131203",
        "size": 0,
        "description": "Wrapper script for GNU autoconf",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "python@FreeBSD.org",
        "name": "python38",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "3.8.12",
        "size": 0,
        "description": "Interpreted object-oriented programming language",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "perl@FreeBSD.org",
        "name": "p5-URI",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "5.09",
        "size": 0,
        "description": "Perl5 interface to Uniform Resource Identifier (URI) references",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "culot@FreeBSD.org",
        "name": "p5-IO-HTML",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.001_1",
        "size": 0,
        "description": "Open an HTML file with automatic charset detection",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "bapt@FreeBSD.org",
        "name": "indexinfo",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "0.3.1",
        "size": 0,
        "description": "Utility to regenerate the GNU info page index",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "yuri@FreeBSD.org",
        "name": "jsoncpp",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "1.9.4",
        "size": 0,
        "description": "JSON reader and writer library for C++",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:14Z"
        },
        "vendor": "ehaupt@FreeBSD.org",
        "name": "bash",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "5.1.8",
        "size": 0,
        "description": "GNU Project's Bourne Again SHell",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:15Z"
        },
        "vendor": "svysh.fbsd@gmail.com",
        "name": "p5-TimeDate",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "2.33,1",
        "size": 0,
        "description": "Perl5 module containing a better/faster date parser for absolute dates",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:15Z"
        },
        "vendor": "tijl@FreeBSD.org",
        "name": "libtool",
        "architecture": "FreeBSD:12:amd64",
        "format": "pkg",
        "version": "2.4.6_1",
        "size": 0,
        "description": "Generic shared library support script",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:15Z"
        },
        "vendor": "sunpoet@FreeBSD.org",
        "name": "p5-CGI",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "4.53",
        "size": 0,
        "description": "Handle Common Gateway Interface requests and responses",
        "agent_id": "002"
      },
      {
        "scan": {
          "id": 0,
          "time": "2021-09-22T11:59:15Z"
        },
        "vendor": "cperciva@FreeBSD.org",
        "name": "firstboot-freebsd-update",
        "architecture": "FreeBSD:12:*",
        "format": "pkg",
        "version": "1.3",
        "size": 0,
        "description": "Update the system using freebsd-update when it first boots",
        "agent_id": "002"
      }
    ],
    "total_affected_items": 57,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified syscollector information was returned",
  "error": 0
}
```
</details>

<details>
  <summary>GET /agents?os.name=FreeBSD</summary>
  
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "amd64",
          "major": "12",
          "minor": "2",
          "name": "FreeBSD",
          "platform": "freebsd",
          "uname": "FreeBSD |freebsd |12.2-STABLE |FreeBSD 12.2-STABLE r370608 GENERIC |amd64",
          "version": "12.2-STABLE"
        },
        "name": "freebsd",
        "dateAdd": "2021-09-21T23:10:59Z",
        "lastKeepAlive": "2021-09-22T12:07:40Z",
        "status": "active",
        "id": "002",
        "mergedSum": "9a016508cea1e997ab8569f5cfab30f5",
        "manager": "centos8.localdomain",
        "version": "Wazuh v4.3.0",
        "node_name": "node01",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "registerIP": "any",
        "group": [
          "default"
        ],
        "ip": "10.0.2.15"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}

</details>


Regards,
Nico

**Closed** 2021-11-05 13:08 UTC
Labels: bug, 4.3
