### ISSUE TITLE
wazuh-registry.json not found

### ISSUE THREAD

**Issue by leszcz** [wazuh/wazuh-kibana-app#2199] opened 2020-04-20 10:31 UTC
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 3.12   | 7.6.4     | 444 |

**Description**
When i installed wazuh on server with Kibana i've got this error:

> 2001 - ENOENT: no such file or directory, open '/usr/share/kibana/plugins/wazuh/server/wazuh-registry.json' (/hosts/apis)

**Steps to reproduce**

1. Go to 'Kibana' -> 'Wazuh'
2. See error

**Screenshots**
None

**Additional context**
I installed a software first time from packages, after it i must upgrade wazuh-app 3.11 to 3.12 with kibana plugin-install but it's not working now.

**Comment by jsanchez91** [comment] 2020-04-20 11:44
Hi @leszcz 

This error is caused by installing the plugin as root.

To solve it, execute this command to change the owner of the plugin files.
```bash
sudo chown -Rf kibana: /usr/share/kibana/plugins/wazuh
```

You can also uninstall the plugin and reinstall it by following the steps in our documentation:
https://documentation.wazuh.com/3.12/installation-guide/installing-elastic-stack/elastic_server_rpm.html#kibana

Let me know if these solutions work for you.

**Comment by leszcz** [comment] 2020-04-20 11:47
It's not working after change owner of directory.

**Comment by jsanchez91** [comment] 2020-04-20 11:48
You may need to restart the Kibana service after the change.

```bash

**Comment by leszcz** [comment] 2020-04-20 12:03
Okay, thanks. Now it's working! :D

**Comment by jsanchez91** [comment] 2020-04-20 13:07
I'm glad I could help you. 
I close the issue but don't hesitate to reopen it or open a new one if you have more doubts.

Regards,
Jose

**Closed by jsanchez91** 2020-04-20 13:07 UTC
Labels: bug, help wanted
