### ISSUE TITLE
Ruleset search not working

### ISSUE THREAD

**Issue by AlexisLessard** [wazuh/wazuh-kibana-app#437] opened 2018-05-02 15:17 UTC
We have installed the Wazuh Plugin on a test Kibana 6.2.4 and connected it to a 6.x stack of elastic search. While everything seems to be in order, I'm having issued when trying to search  a rule in the ruleset of the manager. Whenever I type anything in the ruleset search bar, the following error appears:
![image](https://user-images.githubusercontent.com/10947093/39531133-83f4b984-4df8-11e8-8e7e-df48abb434e1.png)

The error appearing is 

`Error Datahandler factory. Error. Wazuh-Python Internal Error: 'ascii' codec can't encode character u'\xe0' in position 6: ordinal not in range(128)`

As a result, whenever I want to see details of a rule whitout having to go inside the ruleset files on the server, I need to search for the rule in the list, scrolling until I reach the rule id, which is unpracticle considering there are thousands of rules. 
**note**: The same problem does not appear in the decoder search bar. I can search for a decoder easily

**Additionnal Information**
 * Ossec-init.conf content:
`
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.2.1"
REVISION="3220"
DATE="Sat Mar  3 01:02:44 UTC 2018"
TYPE="server"
`
* Kibana Version: 6.2.4
* The wazuh manager is on the same VM as Kibana.

**Comment by JuanjiJG** [comment] 2018-05-03 10:48
Hello @AlexisLessard,

This is a really weird issue, and we'll try to help you with this.

First of all, could you please let me know what's your current OS language on the Wazuh manager/Elasticsearc server, and also the language from your web browser?

Also, I would like to know what characters do you first type on the search bar so the error could be triggered? Maybe that would help us to find the cause of your problem.

Regards,
Juanjo

**Comment by JuanjiJG** [comment] 2018-05-03 16:29
Hello again @AlexisLessard,

Regarding your second message of "Invalid characters", it's a known bug on the Wazuh API and we already have a pending [pull request](https://github.com/wazuh/wazuh-api/pull/76) ready to be merged. This fix will be included in future versions of the Wazuh API.

About your first character encoding problem, let's see what's your current system encoding. Please, open a terminal on the Elasticsearch server and execute the following command:
```bash
locale
```

And please, paste here the output.

Thanks for your patience.

Regards,
Juanjo

**Comment by JuanjiJG** [comment] 2018-05-07 06:55
Hello again @AlexisLessard,

This is an API-related error. The Wazuh app makes an API call to search on the ruleset lists, and the API returns that error messages. I've notified the Wazuh API team about this issue and they'll try to find a solution for this as soon as possible. In the meantime, I would like you to execute some things to see the raw API response when using one of its endpoints.

Please, execute the following commands, replacing with your actual API credentials and URL:
```
curl -u <API_USER>:<API_PASS> http(s)://<API_URL>:55000/rules?search='$(error)'
curl -u <API_USER>:<API_PASS> http(s)://<API_URL>:55000/rules/218?pretty
```

And please, paste here the output.

Thanks for your patience.

Regards,
Juanjo

**Comment by jesusgn90** [comment] 2018-05-10 15:32
Hi @AlexisLessard this is a known bug and it's fixed on https://github.com/wazuh/wazuh-api/pull/76, you'll be able to use more characters such `$`, `(` or `)` on next Wazuh API packages.

Since it's solved I'm going to close this issue. Thank you so much for your feedback, you are always welcome. Don't hesitate to open a new issue if you are facing troubles.

Regards,
Jesús

**Comment by AlexisLessard** [comment] 2018-05-10 15:47
Hello again!
Sorry for the delay in my response. Here are the results of the commands you asked for:

curl -u <API_USER>:<API_PASS> http(s)://<API_URL>:55000/rules?search='$(error)' results in:
{"error":612,"message":"Param not valid. Valid characters: a-z A-Z 0-9 space _ - /  : . \" ' @ ~ +.  Field: search"}
as expected. The other results in that json output:
![image](https://user-images.githubusercontent.com/10947093/39878895-7940a2fa-5447-11e8-9903-eef42b354664.png)

Simple enough. However, when searching for more common characters, I still get an error. Calling this ressource:
http://127.0.0.1:55000/rules?search='sql'
I get this error:
{"error":1000,"message":"Wazuh-Python Internal Error: 'ascii' codec can't encode character u'\\xe0' in position 6: ordinal not in range(128)"} 

Same as the one in the Kibana Plugin. So the issue is not resolved. However we know that the issue is from the API, no the kibana plugin now. I'll try to look for an answer on their git hub. If I can't find it, I'll open an issue on their side.

**Comment by jesusgn90** [comment] 2018-05-10 15:59
Ok @AlexisLessard ,

regarding to special characters such `$`, it's still failing, we are waiting for next packages from Wazuh API.

Regarding to your query using commono characters (`http://127.0.0.1:55000/rules?search='sql'`) I've just tried it:

```
curl foo:bar@localhost:55000/rules?search='sql'
{"error":0,"data":{"totalItems":63,"items":[{"status":"enabled","pci":["10.2.4","10.2.5"],"description":"MS SQL Server Logon Failure.","file":"0220-msauth_rules.xml","level":5,"path":"/var/ossec/ruleset/rules","groups":["win_authentic
....
```

And same result with this:

```
curl foo:bar@localhost:55000/rules?search=sql
{"error":0,"data":{"totalItems":63,"items":[{"status":"enabled","pci":["10.2.4","10.2.5"],"description":"MS SQL Server Logon Failure.","file":"0220-msauth_rules.xml","level":5,"path":"/var/ossec/ruleset/rules","groups":["win_authentic
....
```

Could you execute the same command without `'`, this means `:55000/rules?search=sql`?


Regards,
Jesús

**Comment by AlexisLessard** [comment] 2018-05-10 16:30
There you go, @jesusgn90 . I get the same error:
 http://127.0.0.1:55000/rules?search=sql

{"error":1000,"message":"Wazuh-Python Internal Error: 'ascii' codec can't encode character u'\\xe0' in position 6: ordinal not in range(128)"}

**Comment by jesusgn90** [comment] 2018-05-11 07:20
Hello again @AlexisLessard ,

At this point I think you have added a custom rule to our ruleset or maybe you have modified an existing one. Since we have different results for the same query and similar environments the cause could be a special character inside your rules. Whenever you call the _/rules_ route from the Wazuh API, the API look into the rules files and is throwing an error reading one of them.

Could we be in this scenario?

Regards,
Jesús

**Comment by AlexisLessard** [comment] 2018-05-11 18:30
@jesusgn90 , it is a possibility. We have custom rules that contain special characters such as é (We are a francophone company, so having french characters in our configs is a possibility 😄 ). I can't test this at the moment, but I'll try to do a new search after removing our local_rules.xml file.

**Comment by AlexisLessard** [comment] 2018-05-11 18:56
That did it! If I remove the file /var/ossec/etc/rules/local_rules.xml, the search is working perfectly, wether with a direct api call or within the kibana app. Here's the command I'm using to call the api:
`curl -u xxx:xxx http://127.0.0.1:55000/rules?search=sql`
And I get a nice formated output instead of the usual error. So it would be because there are special characters in our custom rule file? Just to be sure, I'll try to remove all of them. If it does work, I'll modify our custom rules to remove this. However, I'll report an issue in the API to add a feature in the search, so that special characters such as é would be supported. I feel like it would be necessary.

**Comment by JuanjiJG** [comment] 2018-05-11 19:01
Hello again @AlexisLessard,

That's great, we finally found the problem! This is an issue that the Wazuh API team must work on, so don't hesitate to open an issue on [its repository](https://github.com/wazuh/wazuh-api) so the can give you better tracking of the progress.

Now I'll proceed to close this issue. Thanks so much for your patience and for your valuable feedback, w definitely have to work on more compatibility to special characters, such as the French ones.

Best regards,
Juanjo

**Closed by JuanjiJG** 2018-05-11 19:01 UTC
Labels: bug, frontend, help wanted, research
