### ISSUE TITLE
Facing Issues adding API

### ISSUE THREAD

**Issue by HUssain14** [wazuh/wazuh-kibana-app#291] opened 2018-03-05 12:55 UTC
After successfully installing OSSEC Server and (ES +LS+K) now im trying to create connection between app and api but not able to add the new api. i try this command from wazhu app & it works 

curl -u foo:bar "ip:55000/?pretty"{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.2.1",
      "hostname": "ip",
      "timestamp": "Mon Mar 05 2018 12:44:36 GMT+0000 (UTC)"
   }
}

but when im trying to add from browser I'm facing issues in URL bar only. when i use ip over there it shows error of checking the port but all ports are open and accessible I successfully telnet the port i.e 55000. I'm clueless over here what is the actual issue right now. Here is the error log 

{"type":"response","@timestamp":"2018-03-05T12:44:29Z","tags":[],"pid":5359,"method":"post","statusCode":500,"req":{"url":"/api/wazuh-api/checkAPI","method":"post","headers":{"host":"localhost:5601","user-agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0","accept":"application/json, text/plain, */*","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","referer":"http://localhost:5601/app/wazuh","content-type":"application/json","kbn-version":"6.2.2","content-length":"202","connection":"keep-alive"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://localhost:5601/app/wazuh"},"res":{"statusCode":500,"responseTime":85,"contentLength":9},"message":"POST /api/wazuh-api/checkAPI 500 85ms - 9.0B"}

Looking for assistance.
/etc/kibana# cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.2.1",
    "version": "6.2.2"
root@ip:/etc/kibana#  curl localhost:9200 -s | grep number
    "number" : "6.2.2",

**Comment by jesusgn90** [comment] 2018-03-05 14:06
Hi @HUssain14 , assuming you are referring the following error:

```Settings. Wrong Wazuh API port, please check it and try again```

whenever you click on `SAVE API` button.

Could be two main reasons to fall on that error. The Kibana machine is unable to connect with the Wazuh API machine or the Wazuh API is down. You said that a `curl` command directly to the Wazuh API give you a response so we are on the first case I think.

It's important that you take in care about the data flow:

Kibana UI (your browser) make a request (`/api/wazuh-api/checkAPI`) to the Kibana machine(where the backend lives), the Kibana machine make a request to the Wazuh API machine. The Wazuh API returns a response to the Kibana machine and then it returns a response to the Kibana UI. Since you are seeing the Kibana UI the first step is fine, maybe the problem is between the Kibana machine and the Wazuh API.

Login through ssh on the Kibana machine and do the same curl as you said (`curl -u foo:bar "ip:55000"`).

Another problem that could be happening here is that the Kibana machine doesn't know who is `ip` if you are using it as hostname, try to fill the url with the IP to discard any error related to this. So if your hostname named `ip` has the IP `10.0.0.2` (example) you should fill the form as follow:

```
user: foo
pass: bar
url:  http://10.0.0.2 // If the Kibana machine is the same as the Wazuh API http://localhost
port: 55000
```
Also it should be fine for us if you give us some screenshot when you are trying to add the Wazuh API with the dev tools of your browser opened. Also if the request did fail, you could open the network tab under dev tools to see the exact response of the failed request to paste here too.

Best regards,
Jesús

**Comment by HUssain14** [comment] 2018-03-07 05:26
Already do the curl as you said (curl -u foo:bar "10.0.0.2:55000") from kibana machine and response is same it is connecting successfully 
"error": 0,
"data": {
"msg": "Welcome to Wazuh HIDS API",
"api_version": "v3.2.1",
"hostname": "ip",
"timestamp": "Mon Mar 05 2018 12:44:36 GMT+0000 (UTC)"
}
}

Issue over Kibana UI actually you are right im facing this error 
"Settings. Wrong Wazuh API port, please check it and try again"

when i input localhost in url box it starting to show error on port (i.e check your port) and when i enter ip of wazhu api 10.0.0.2 it shows the above error but on curl with ip it is working fine. Wazhu API is up and accessible from browser.

**Comment by jesusgn90** [comment] 2018-03-07 08:32
Ok @HUssain14 the error `'Could not connect with Wazuh API, please check url and port and try again'` is shown whenever the backend catch a `socket hang up` error. We are going to make some checks in order to discard timeout related errors. 

Go to your Kibana machine through ssh and execute the next command:

```# sed -i 's/#timeout: 4000/timeout: 20000/g' /usr/share/kibana/plugins/wazuh/config.yml```

Ensure that sed command worked:

```# cat /usr/share/kibana/plugins/wazuh/config.yml | grep timeout```

Restart Kibana:

```# systemctl restart kibana```

Open a new incognito window on your desired browser and open the dev tools([Chrome dev tools](https://developer.chrome.com/devtools)), keep opened the network tab of the dev tools. Try to add the Wazuh API one more time using different ways (using directly the IP, etc.), note down the request response error shown on the dev tools. Please paste here each noted response, thanks.

Best regards,
Jesús

**Comment by HUssain14** [comment] 2018-03-07 08:59
![screenshot from 2018-03-07 13-59-14](https://user-images.githubusercontent.com/36950281/37082939-b747c516-220f-11e8-8dfa-8efc911c21de.png)

Response:
"Statuscode:500" "error:5" "message:there is no database for selected agent"

**Comment by jesusgn90** [comment] 2018-03-07 09:43
Ok @HUssain14 then your problem seems to be a corrupt database. Please execute the following command (on the Wazuh manager machine):

```# rm -f /var/ossec/var/db/global.db*```

It will remove the main Wazuh manager database, the information will be regenerated after a restart so please execute the next command (on the Wazuh manager machine):

```# /var/ossec/bin/ossec-control restart```

Once done, try again to add your Wazuh API on the Wazuh App, it should fix your problem.

King regards,
Jesús

**Comment by HUssain14** [comment] 2018-03-07 11:30
thank you it works.

**Comment by jesusgn90** [comment] 2018-03-07 11:39
Happy to help @HUssain14 , since it works I'm going to close the issue. Open a new issue if you are facing any more trouble.

Best regards,
Jesús

**Closed by jesusgn90** 2018-03-07 11:39 UTC
Labels: api, help wanted, kibana
