### ISSUE TITLE
Redesign the agent's dashboard 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-kibana-app#4238] opened 2022-06-09 15:36 UTC
**Describe the solution you'd like**

In the agent's dashboard, there is an SCA card with a severity indicator of the last SCA scan made for that agent. It is not clear how we're selecting the policy or if we're agregating them in those indicators.

![image](https://user-images.githubusercontent.com/2181918/172886810-8dc5895d-0ef1-4894-b30e-526baf7c10a2.png)

A user needs to go through three pages to reach a list of the failing policies. We want to take the user to the information without going through all these pages.

![image](https://user-images.githubusercontent.com/2181918/172886902-a203d38c-d519-4ef8-b922-e09a644ce39c.png)

We need to design the widget in a way the user can reach the information weŕe displaying with a single click. 

We will discuss possible designs as well as their  implementation in this issue.

**Comment by chantal-kelm** [comment] 2022-07-19 15:21
I think this could be a solution, more intuitive for the user: https://user-images.githubusercontent.com/99441266/179787358-49c6d8a7-048c-48ec-9301-759f374707bc.mp4

**Comment by chantal-kelm** [comment] 2022-09-14 18:03
Today I took the issue and have been working on understanding how the filters are being passed through the url and based on that displaying certain tables.
Once I understood this, I rendered the table where we want, I still need to keep working on this issue.

**Comment by chantal-kelm** [comment] 2022-09-14 18:17
This issue was due tomorrow but due to many changes from the ci cd team on this [issue](https://github.com/wazuh/wazuh-packages/issues/1625), I was able to start it today and will change the due date.

**Comment by chantal-kelm** [comment] 2022-09-16 16:47
### **Desired behavior:**

When we click on a row of the table we want to show in the SCA card: 'Latest scans' we want it to redirect us to a new page where we will show the second table.

### **Research:**
Currently, the routes of the project are made with Angular, and the same route shows different screens depending on the states that are changing, so there is no specific route as there should be. This also happens in the section we want to redesign.
So when we want to redirect as in this case when clicking on a row we don't have a URL to redirect to.
In the future, it would be good to finish moving the project to React, and include the React router dom that would solve these problems.

### **Proposed solution:**
According to what I discussed with my colleague Antonio and seeing how the current development is, the best option will be to click on a row, pass some parameters by URL and if those parameters are present in the URL show the table we want, handling the states to behave as we expect, taking into account that this section handles states and filters for the tables, all this should coexist with the new development.

**Comment by chantal-kelm** [comment] 2022-09-20 17:57
Today I have been working on setting the corresponding states.

**Comment by chantal-kelm** [comment] 2022-09-23 16:42
While this issue was being developed, it was noticed that there was an error with the policy_id when making a request to the Wazuh API. It was not clarified if it could be a problem of the Wazuh API or if the problem is of the library used to make the requests when using a value containing invalid characters.
An issue will be opened, and it will be investigated whether the problem is API or library related.

An investigation was done to see if the policy_id could contain invalid characters that cause the same problem that was detected in a development.

We consulted with Core and received the following response:
Currently, no validation is done for this field beyond it being a string, at least at the core level, until it is stored in the DB. Then it is the API that queries it until it ends up in the UI, but I doubt that there are currently any restrictions in the API as well.
Surely then this field can contain characters that cause the problem you mention in the app, in that case it would be good to put a validation and know which characters should be invalid.

We will open an issue about this and continue with the topic.


On the other hand when you click on the table of the SCA card and make the redirection it is checked that the relevant states are set and that the url is or not present a paurameter, based on these states and parameter it is decided whether to display a table or another.
As the redirection showed for a second a table and then finished making the check and showed another, to improve the user experience it was decided to put a loading that the user sees while behind the checks are made of parameters and states and decide which table to show, I'm currently working on the latter.

**Comment by Machi3mfl** [comment] 2022-10-19 18:18
I added a new issue to treat the implementation and improve the current solution: [Refactor Agent SCA Inventory](https://github.com/wazuh/wazuh-kibana-app/issues/4719).
This refactor will improve the code `readability, reusability, and performance.` It's not a UI refactor

**Comment by Machi3mfl** [comment] 2022-10-20 14:53
### Video showing the new design and navigation

https://user-images.githubusercontent.com/6089438/196983275-68b36196-bc74-45df-aaa0-600c36bb7dfc.mp4


### Video showing the SCA: Lastest scan with pagination

https://user-images.githubusercontent.com/6089438/196983300-bc77fd07-e745-47f2-9c4f-c6ccbe1dbe25.mp4

**Closed** 2022-10-24 08:00 UTC
Labels: enhancement, cat-3
