### ISSUE TITLE
Query bar search bug in Safari macOS

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [wazuh/wazuh-kibana-app#2912] opened 2021-02-03 09:23 UTC
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0  | 7.10.0     | 4101-1 |

Hi team,
We've found that in Safari `13.0.1 (14608.2.11.1.11)` multiple queries like` "rule.level >= 10 and agent.name : "pop-os""` are not working. 

As an example here is the query in firefox Linux. In `Modules/Security events`:
![image](https://user-images.githubusercontent.com/44369304/106723172-1fd83780-6607-11eb-98c7-ebf5d31d4fe5.png)

Same query in Sarafi macOS:
![image](https://user-images.githubusercontent.com/44369304/106723655-a12fca00-6607-11eb-80f6-0bfd563f4118.png)

Also many pop up error windows are spawned with 1 query when only 1 should spawn.

We should investigate both issues:
- Multi query error.
- Multiple errors pop up.

Regards,
Víctor.

**Comment by VictorMorenoJimenez** [comment] 2021-02-05 12:06
After several tries, @pablomarga was not able to reproduce the error. We've found that the query error was for using VirtualBox to introduce the `"` characters. When using it outside VirtualBox works fine.

However, we still have multiple pop up windows bug. This bug happens in any browser, not only Safari.

https://user-images.githubusercontent.com/44369304/107031620-c3b21680-67b2-11eb-8bbe-c4a48a6a3369.mp4

**Comment by pablomarga** [comment] 2021-02-11 08:09
Hi, after investigate it we have found that this error is caused by kibana and not by the Wazuh plugin itself, so I am closing this issue.
Regards.

**Closed by pablomarga** 2021-02-11 08:09 UTC
Labels: bug, cicd
