### ISSUE TITLE
kibana-plugin install error

### ISSUE THREAD

**Issue by bloodzer0** [wazuh/wazuh-kibana-app#663] opened 2018-07-04 00:39 UTC
kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.3.1_6.3.0.zip 

then：
Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false --uiSettings.enabled=false
(node:13995) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

how to solve？

**Comment by JuanjiJG** [comment] 2018-07-04 06:33
Hello @bloodzer0,

Sorry for the inconveniences trying to install our app. Let's try to solve this.

1. First of all, could you please tell me what's your current Kibana version? You can use this command:
```
cat /usr/share/kibana/package.json | grep "version"
```
2. Are you trying to upgrade from a previous version of the Wazuh app?

Thanks in advance for your patience.

Regards,
Juanjo

**Comment by bloodzer0** [comment] 2018-07-05 07:20
I have solved the problem,I updated the version of nodejs.thanks

**Comment by havidarou** [comment] 2018-07-06 16:56
Hi @DarioBalinzo ,

let's install nodejs and see if that fixes the issue.

For RPM systems:

1. Download package:
```curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -```

2. Install it:
```yum install nodejs```

For DEB systems:

1. Download package:
```curl -sL https://deb.nodesource.com/setup_8.x | bash -```

2. Install it:
```apt-get install nodejs```

Then try to install the app again.

Hope that helps.

Best regards.

**Comment by 2m12m1** [comment] 2018-09-12 07:54
I have the same error following the upgrading to 6.4.0
and i upgrading my nodejs to nodejs.x86_64 2:8.12.0-1nodesource  

but no fix.

regards

**Comment by jesusgn90** [comment] 2018-09-12 08:00
Hi @2m12m1 ,

Please, try to stop Kibana service and starting it in foreground mode:

```
systemctl stop kibana
/usr/share/kibana/bin/kibana -c /etc/kibana/kibana.yml --verbose
```
Once you are done, press CTRL + C to stop foreground mode. The idea behind this is to force Kibana show us more in deep information, this way we can catch easier your problem.

Regards,
Jesús

**Comment by 2m12m1** [comment] 2018-09-12 08:13
/usr/share/kibana/bin/kibana -c /etc/kibana/kibana.yml --verbose
  log   [08:12:06.771] [debug][plugin] Found plugin at /usr/share/kibana/node_modules/x-pack
  log   [08:12:06.802] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/apm_oss
  log   [08:12:06.824] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/console
  log   [08:12:06.840] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/elasticsearch
  log   [08:12:06.841] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/input_control_vis
  log   [08:12:06.842] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/inspector_views
  log   [08:12:06.843] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kbn_doc_views
  log   [08:12:06.844] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kbn_vislib_vis_types
  log   [08:12:06.894] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/kibana
  log   [08:12:06.900] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/markdown_vis
  log   [08:12:06.901] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/metric_vis
  log   [08:12:06.954] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/metrics
  log   [08:12:06.955] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/region_map
  log   [08:12:06.956] [warning][plugin] Skipping non-plugin directory at /usr/share/kibana/src/core_plugins/spy_modes
  log   [08:12:06.957] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/state_session_storage_redirect
  log   [08:12:06.958] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/status_page
  log   [08:12:06.960] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/table_vis
  log   [08:12:06.961] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/tagcloud
  log   [08:12:06.962] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/tile_map
  log   [08:12:06.963] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/timelion
  log   [08:12:06.966] [debug][plugin] Found plugin at /usr/share/kibana/src/core_plugins/vega
 error  [08:12:07.991] [fatal] Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (/usr/share/kibana/node_modules/del/index.js:18:9)
    at mapper (/usr/share/kibana/node_modules/del/index.js:33:4)
    at Promise.resolve.then.el (/usr/share/kibana/node_modules/p-map/index.js:46:16)
    at <anonymous>
FATAL Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (/usr/share/kibana/node_modules/del/index.js:18:9)
    at mapper (/usr/share/kibana/node_modules/del/index.js:33:4)
    at Promise.resolve.then.el (/usr/share/kibana/node_modules/p-map/index.js:46:16)
    at <anonymous>

**Comment by 2m12m1** [comment] 2018-09-12 08:14
and after installation request its show this:

**Comment by jesusgn90** [comment] 2018-09-12 08:47
Hi @2m12m1 ,

The main problem here I thinks is `ENOMEM`, it means out of memory error. If you are out of memory, the installation will fail always, see http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html for details. 

Once you are done with the memory, we can continue.

Regards,
Jesús

**Comment by 2m12m1** [comment] 2018-09-12 09:17
dear Jesús
i dont have any problem with older version. and with another packages
i just find this problem with upgrading wazuh in the kibanna task
regards

**Comment by 2m12m1** [comment] 2018-09-12 09:28
Dear Jesús

**Comment by jesusgn90** [comment] 2018-09-12 09:32
Happy to help @2m12m1 !

Closing this, reopen it or create a new ticket if you fall again into this situation.

Best regards,
Jesús

**Closed by jesusgn90** 2018-09-12 09:32 UTC
Labels: bug, help wanted

**Comment by AdjiDarmawan** [comment] 2018-12-04 11:53
> I'm glad your problem got solved @bloodzer0.
> 
> If you need more help with anything about Wazuh, don't hesitate to open a new issue.
> 
> Regards,
> Juanjo

Hi Juanjo,

I have same bloodzer0 problem. 

"Plugin installation was unsuccessful due to error "Command failed: /usr/share/kibana/node/bin/node /usr/share/kibana/src/cli --env.name=production --optimize.useBundleCache=false --server.autoListen=false --plugins.initialize=false"

I use Kibana 5.6.1 and wazup app 3.7.0 and I have installed nodejs version 8.14.0. But the problem still remains the same. are there other solutions for improvement. thank you

**Comment by jesusgn90** [comment] 2018-12-04 12:05
Hello @AdjiDarmawan ,

Currently, we are not supporting Wazuh 3.7.0 and Elastic 5.6.1, you can read about our compatibility matrix at https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#api-and-kibana-app. There you can check which versions fit your requirements. The Wazuh app must match both Wazuh and Elastic specific versions, otherwise, it won't work properly.

On the other hand, we suggest upgrading Elastic too because it has a lot of improvements and bug fixes. 

![image](https://user-images.githubusercontent.com/8860227/49440859-1f447c00-f7c5-11e8-8b09-aed81eea0974.png)

- https://github.com/wazuh/wazuh-kibana-app#older-packages

Our latest supported versions are Wazuh 3.7.0 (3.7.1 coming soon) and Elastic 6.5.1 (6.6.0 coming soon). Our upgrading from different major versions: https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html

I hope it helps.

Best regards,
Jesús

**Comment by AdjiDarmawan** [comment] 2018-12-05 08:20
Hello @jesusgn90,



> Hello @AdjiDarmawan ,
> 
> Currently, we are not supporting Wazuh 3.7.0 and Elastic 5.6.1, you can read about our compatibility matrix at https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#api-and-kibana-app. There you can check which versions fit your requirements. The Wazuh app must match both Wazuh and Elastic specific versions, otherwise, it won't work properly.
> 
> On the other hand, we suggest upgrading Elastic too because it has a lot of improvements and bug fixes.
> 
> ![image](https://user-images.githubusercontent.com/8860227/49440859-1f447c00-f7c5-11e8-8b09-aed81eea0974.png)
> 
>     * https://github.com/wazuh/wazuh-kibana-app#older-packages
> 
> 
> Our latest supported versions are Wazuh 3.7.0 (3.7.1 coming soon) and Elastic 6.5.1 (6.6.0 coming soon). Our upgrading from different major versions: https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.html
> 
> I hope it helps.
> 
> Best regards,
> Jesús

Hi jesusgn90,

sorry about my comment above, there was a typo related to the ELK version that I was using. In the information I wrote earlier for the ELK version that I used is version 5.6.1, while the real one is version 6.5.1.

and I have done the installation process in accordance with the documentation from the official Wazuh website (https://documentation.wazuh.com/current/installation-guide/index.html)

but the problem still remains the same. Please help. Thank you

Noted:
I use Centos 7.6.1810

**Comment by jesusgn90** [comment] 2018-12-05 08:31
Hi @AdjiDarmawan ,

Have you tried with the next command?

```
sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.7.0_6.5.1.zip
```
Exactly the same?

On the other hand, how much memory has your instance? What we are telling Node.js using `"--max-old-space-size=3072` is "you can use up to 3GB RAM". The app installation usually has a peak of about 1.9GB of RAM, once it's installed and running this amount of memory goes down.

Best regards

**Comment by AdjiDarmawan** [comment] 2018-12-05 09:41
Hi jesusgn90,

yess ... the problem is done and resolve, The problem is in memory capacity instances that do not meet, before I used the memory of 4 GB and after I upgraded it to 8 GB, the installation process wazuhapp runs smoothly until the installation process is finished properly.

Thanks jessusgn90 and Thank you to all of you

**Comment by jesusgn90** [comment] 2018-12-05 09:42
Always happy to help @AdjiDarmawan !!!

Regards
