### ISSUE TITLE
Incompatible dependency `triple-beam@1.4.0`

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-kibana-app#5650] opened 2023-07-10 09:22 UTC
| Wazuh | Elastic | Rev  |
| ----- | ------- | ---- |
| 4.4.5 | 7.10.2 | 01 |

## Description
`triple-beam` 1.4.0 has been released a few hours ago. This new version is incompatible with the Node version for our plugin for Kibana 7.10.2.

Our plugin build correctly last Friday, before this new version was released. Today, the building fails.

`triple-beam` is a dependency of `winston`, which we use in the plugin.

```
09:46:34  [2/4] Fetching packages...
09:46:34  error triple-beam@1.4.0: The engine "node" is incompatible with this module. Expected version ">= 16.0.0". Got "10.23.1"
09:46:34  error Found incompatible module.
```

### Sources

[triple-beam](https://www.npmjs.com/package/triple-beam) 
[winston](https://github.com/winstonjs/logform/blob/master/CHANGELOG.md)

**Comment by Desvelao** [comment] 2023-07-10 11:08
# Research

| Platform | NodeJS version | Winston version | triple-beam version | 
| --- | --- | --- | --- |
| Kibana 7.10.2 | 10.23.1 | 3.5.1 | ^1.3.0 |
| Kibana 7.16-7.17 | 16.13.0 | 3.9.0 | ^1.3.0 |
| Wazuh dashboard | 14.20.1 | 3.5.1 | ^1.3.0 |

The problem is caused because the package manager is resolving the version of `triple-beam` sub-dependency to version `1.4.0` that has specified the NodeJS engine. https://github.com/winstonjs/triple-beam/blob/v1.4.0/package.json#L38.

There was a new release (1.4.0) for the `triple-beam` package 3 days ago.
![image](https://github.com/wazuh/wazuh-kibana-app/assets/34042064/9f2ca48f-0660-4445-8171-ce5a172e9d1a)

**Closed** 2023-07-10 11:34 UTC
Labels: type/bug, request/operational, level/task
