### ISSUE TITLE
Rule Groups are not listed in Active Response Configuration

### ISSUE THREAD

**Issue by jburleson** [wazuh/wazuh-kibana-app#350] opened 2018-04-03 17:23 UTC
Wazuh App v3.2.1
Kibana v6.2.3

While checking my configuration for the manager (Manager->Configuration->Active Response), I noticed that any AR created using rule groups, does not display the group. ARs that are created with a rule id show the associated rule though.

![wazuh_app](https://user-images.githubusercontent.com/2708757/38263449-c2c49456-3735-11e8-8ef3-acb6c3462bce.PNG)

From ossec.conf on the server.
```
  <active-response>
    <command>firewall-drop</command>
    <location>all</location>
    <rules_id>5712</rules_id>
    <timeout>600</timeout>
  </active-response>

  <active-response>
    <command>firewall-drop</command>
    <location>all</location>
    <rules_group>authentication_failures</rules_group>
    <timeout>600</timeout>
  </active-response>
```

**Comment by JuanjiJG** [comment] 2018-04-04 07:17
Hello @jburleson,

Thank you very much for your report! The team will take a look at this as soon as possible, and we'll keep you up to date when we find out what might be the cause.

Also, I would like to thank you for sharing your Active Response configuration, that will help us a lot for researching about this problem!

Best regards,
Juanjo

**Comment by jesusgn90** [comment] 2018-04-04 08:58
Hi @jburleson,

we just fixed this issue on https://github.com/wazuh/wazuh-kibana-app/commit/73be9598e1cdb54dcfeb69059c3b5314520b2dcd, and here is an example `ossec.conf` using one `rules_id`, using two `rules_id` and using `rules_group`. Also an screenshot is attached. On the other hand you need to wait to next packages to see this on action because the commit is on one of our development branches. Thanks for your patience and thanks for your feedback. 

```xml
 <active-response>
    <command>firewall-drop</command>
    <location>all</location>
    <rules_id>5712,5713</rules_id>
    <timeout>600</timeout>
  </active-response>
  <active-response>
    <command>test-command</command>
    <location>all</location>
    <rules_id>5712</rules_id>
    <timeout>600</timeout>
  </active-response>
  <active-response>
    <command>firewall-drop</command>
    <location>all</location>
    <rules_group>authentication_failures</rules_group>
    <timeout>600</timeout>
  </active-response>
```

![fix](https://user-images.githubusercontent.com/8860227/38298015-677925e6-37f6-11e8-9cf9-cc67b6f6e29d.png)

As I said, this is now solved, so I'm going to close this issue. Feel free to open a new issue if it's needed, have a nice day.

Best regards,
Jesús

**Closed by jesusgn90** 2018-04-04 08:58 UTC
Labels: api, bug, frontend

**Comment by jburleson** [comment] 2018-04-04 11:00
Thanks for the quick response and fix!

**Comment by jesusgn90** [comment] 2018-04-04 11:02
You are welcome!
