### ISSUE TITLE
Wazuh app doesn't open under custom spaces

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-kibana-app#1234] opened 2019-02-12 15:25 UTC
As you know, 6.x introduced spaces as a way to manage collections of visualization, dashboards, etc. Selecting a custom space, and trying to open the wazuh app yields a blank screen. See screenshot below.

Wazuh 3.7.2 + Kibana 6.5.4

![image](https://user-images.githubusercontent.com/2720787/52646261-5c6e6e00-2eda-11e9-8a0c-73ff106a4987.png)

**Comment by jesusgn90** [comment] 2019-02-13 08:24
You are right @rossengeorgiev , we've added this to our roadmap and it will be fixed soon, thanks for your feedback. I'll copy here our progress dealing with Kibana spaces.

Best regards

**Comment by rhysxevans** [comment] 2019-05-21 17:58
Hi

Will this fix allow the Wazuh app to "default" to a specified wazuh-alerts index ?

I am investigating the option of multitenancy via spaces , now that some of the security has been released into the basic subscription

Or do we still need to run multiple Kibana instances to get this done?  (using searchguard)

Thanks

**Comment by jesusgn90** [comment] 2019-05-23 14:14
Hi @rhysxevans ,

I think it will filter index patterns, so it will filter indices too, but it won't disable the index pattern creation menu from Kibana. 

In any case, we are working on it right now, I'll update this issue with any news into this.

Thanks for your patience.

Regards

**Comment by jesusgn90** [comment] 2019-05-23 14:16
Related: https://github.com/wazuh/wazuh-kibana-app/issues/1450

**Comment by rhysxevans** [comment] 2019-05-23 15:44
Thank you

**Comment by jesusgn90** [comment] 2019-05-23 15:53
For refreshing the known fields, we must add a condition for custom spaces.

Before:

```js
await wzWrapper.updateIndexPatternKnownFields('index-pattern:' + item.id);
```

After:
```js
 const prefix = item.namespace ? `${item.namespace}:index-pattern:` : 'index-pattern:';
 await wzWrapper.updateIndexPatternKnownFields(`${prefix}${item.id}`);
```

**Comment by jesusgn90** [comment] 2019-05-23 16:38
More news, the Wazuh monitoring pattern under custom spaces is now being created if it's missing (https://github.com/wazuh/wazuh-kibana-app/commit/eb1eacfe95dea411d6f3bc20e4507e5443bc079f).

Right now this is the status for custom spaces:

- The app doesn't crash regardless of the namespace being used. 
- Monitoring pattern is created if it's missing for that space. 
- Alert patterns known fields are being refreshed as expected under custom spaces. 
- Monitoring pattern known fields are not being refreshed under custom spaces. 
- The Wazuh app is filtering the patterns depending on the current namespace (@migruiz4).  

@rhysxevans you'll have a Wazuh app working under custom spaces soon! In addition, we want to say that we still remember the "multitenancy" question you did, let me continue with the implementation and we'll update you as soon as we can.

**Comment by jesusgn90** [comment] 2019-05-24 15:30
Hi @rhysxevans ,

Today we've fixed the two timelion visualizations under Management > Cluster for custom spaces -> https://github.com/wazuh/wazuh-kibana-app/commit/ace891f12848fdd0a3fef60ab47971280461271f

We've also fixed the top agent request for Agents preview -> https://github.com/wazuh/wazuh-kibana-app/commit/2ce377cdff79a3ecb9869da7974c2ede12df26be

The task is still in progress but I think the next minor version of Wazuh may include it.

Regards

**Comment by jesusgn90** [comment] 2019-05-27 09:09
Here https://github.com/wazuh/wazuh-kibana-app/commit/d6307eb01c5e314b17ba3189856dd8f031ef901b we propagate the namespace as a field for new monitoring patterns, otherwise, the app would think it doesn't exist and would try to create a new one.

**Comment by jesusgn90** [comment] 2019-05-27 10:26
With https://github.com/wazuh/wazuh-kibana-app/commit/830014423a5df77df449d9c2903a9c882ae3425a, the reporting module can handle custom namespaces too just adding the proper parameter when `searchWazuhAlertsWithPayload` is called from the module.

**Comment by jesusgn90** [comment] 2019-05-27 14:48
Current status:

- The app opens regardless of the active space.
- Monitoring pattern is created if missing regardless of the active space.
- Default alerts pattern is not created if missing for custom spaces.
- Alerts patterns known fields are being refreshed for all spaces.

At this point, the task is almost done but a lot of testing is needed.

**Comment by jesusgn90** [comment] 2019-06-06 09:59
Branch: https://github.com/wazuh/wazuh-kibana-app/tree/fix-custom-spaces-1234

**Comment by juankaromo** [comment] 2019-06-12 11:37
**Some testing**

When testing the branch in a development environment, the following error appears.

![image](https://user-images.githubusercontent.com/21195730/59348247-ed354900-8d16-11e9-8322-32d771f8ed68.png)

The first time you access the app with a newly created space [awesome] (now in a production environment) the following error appears. (Cannot find index patterns) 

![image](https://user-images.githubusercontent.com/21195730/59348272-f6261a80-8d16-11e9-9596-f113f709af6e.png)

The monitoring index-pattern is not created.

![image](https://user-images.githubusercontent.com/21195730/59348290-00481900-8d17-11e9-9d8e-cf82c0b31a1f.png)

After creating the `wazuh-alerts` index pattern the app loads correctly.

**Comment by juankaromo** [comment] 2019-06-13 14:47
**Update testing**

All tests have been performed with the default .kibana index.

**Index patterns**
-   `wazuh-alerts-3.x-*` is not created automatically, but is expected behavior ✅
-   `wazuh-monitoring-3.x-*` is not created automatically, and is not created until you access Overview (created when you build the visualizations). It would be necessary to correct it because in the health check it fails. ⚠
-   After creating it, the app loads correctly. ✅

**API management checks**
All tests have been carried out successfully. ✅

**Basic functions in dashboards and overviews (General and Agents) checks (included Filter checks)** 
All tests have been carried out successfully. ✅

**Management tab checks**
All tests have been carried out successfully. ✅

**Agents tab checks**
All tests have been carried out successfully. ✅

**Comment by juankaromo** [comment] 2019-06-21 10:32
**Production error pointing**

I've been getting this error when installing the app in production from the package and updating the `.wazuh-version` index to the log file:

![image](https://user-images.githubusercontent.com/21195730/59916838-8c95c280-9420-11e9-8fcf-be9cdc3bc314.png)

As the calls have changed from `/elastic/timestamp` to `/api/timestamp` it was strange to me that calls were still being made to the previous route.

In the end it was because the bundles generated had not been updated. I proceed to erase them and launch Kibana again to regenerate them.

`rm -rf /usr/share/kibana/optimize/bundles`
`systemctl restart kibana`

Now everything works properly.

**Closed** 2019-07-12 14:43 UTC
Labels: bug, community, delayed, priority/medium
