### ISSUE TITLE
Wazuh-Alerts

### ISSUE THREAD

**Issue by Aldugama** [wazuh/wazuh-kibana-app#1868] opened 2019-11-04 09:49 UTC
Hello, I'm installing Wazuh v3.10.2 along with ELK but I don't know how to activate and download the wazuh-alerts template.

I really need help.

I'm using CentOS.

**Comment by pablotr9** [comment] 2019-11-04 09:55
Hi @Aldugama ,

Is Filebeat installed? Filebeat reads the alerts generated by Wazuh and it sends those alerts to Elasticsearch.

Did you follow the `Installing filebeat` section in our documentation? (You can find that guide here: https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.html#installing-filebeat).  It explains how to install Filebeat, how to install the Wazuh module and how to insert the Wazuh template to Elasticsearch.

Best regards,
Pablo Torres

**Comment by Aldugama** [comment] 2019-11-04 10:03
Helo @pablotr9 ,

Yes, Filebeat is installed, I followed the documentation step by step.

**Comment by pablotr9** [comment] 2019-11-04 10:08
Hi @Aldugama ,

Could you give me some more information? What is exactly your problem? all the components are installed (Elasticsearch,Kibana,Filebeat,Wazuh) but you are not receiving Wazuh alerts into your Elasticsearch? 
Is it a fresh installation or did you upgrade from an older version?

**Comment by Aldugama** [comment] 2019-11-04 10:18
Yes, it's a completely fresh installation. I get 2 errors, 

The agents are not being read:
![kibana-agent-failed](https://user-images.githubusercontent.com/38432205/68113466-28b5f700-fef4-11e9-97da-5e16f452d4c9.jpg)

Elasticsearch template fails at load, 
![elasticsearch-template-failed](https://user-images.githubusercontent.com/38432205/68113609-7b8fae80-fef4-11e9-80c2-0c4c05611d03.jpg)

When I look at the activated templates, I can see that the Wazuh-alert template is not active.
![templates](https://user-images.githubusercontent.com/38432205/68113624-81858f80-fef4-11e9-8d27-e50eab382943.jpg)

**Comment by pablotr9** [comment] 2019-11-04 10:30
Hi @Aldugama ,

Ok thanks for the information. Let's fix your issue, we will check that all components are correctly configured.
We will start with **Filebeat**:
1. Could you please share with us your `filebeat.yml`, you can find that file here:
`/etc/filebeat/filebeat.yml`
2. Now check `wazuh-template.json`, this file is located in:
`/etc/filebeat/wazuh-template.json`
3. Test if Filebeat can connect to Elasticsearch:
`filebeat test output` 
4. Check if Wazuh module is installed:
`cat /usr/share/filebeat/module/wazuh/module.yml`


Please paste the output of above commands in a file and attach it to your reply. 

Best regards,
Pablo Torres

**Comment by Aldugama** [comment] 2019-11-04 10:56
The filebeat test, was working perfectly, and I don't know the reason why it stopped working (it might have something to do with the kibana.yml file in which I changed the IP address from localhost to the real IP the machine has).
![filebeat test](https://user-images.githubusercontent.com/38432205/68115941-db3c8880-fef9-11e9-9074-278050cc5772.jpg)
![filebeat yml](https://user-images.githubusercontent.com/38432205/68115942-db3c8880-fef9-11e9-8e5a-73d2c0bc67e6.jpg)
![module](https://user-images.githubusercontent.com/38432205/68115943-dbd51f00-fef9-11e9-8f48-c3bb541a5085.jpg)
[wazuh-template.txt](https://github.com/wazuh/wazuh-kibana-app/files/3803639/wazuh-template.txt)

**Comment by pablotr9** [comment] 2019-11-04 11:27
Hi @Aldugama ,

It seems that the problem is in Logstash.  Do you need Logstash for any specific purpose? (for example data transformations) if you don't need it you can uninstall it and use only Filebeat.
Filebeat can send the logs directly to Elasticsearch wtihout using Logstash, to do that you only have to change the last line of your `filebeat.yml` with this:
```
#output.logstash.hosts: ['localhost:5000'] 
output.elasticsearch.hosts: ['ELASTIC_IP:9200'] # replace ELASTIC_IP with the IP of the Elasticsearch server 
```

Let me know if you need Logstash or if only Filebeat is enough for you, so I can give you further assistance.

Best regards,
Pablo Torres

**Comment by Aldugama** [comment] 2019-11-04 11:32
I need to read logs from a Fortigate firewall and I thought it would be useful to use Logstash, maybe I don't really need it, I would be greatful if you confirm that, please.

**Comment by pablotr9** [comment] 2019-11-04 11:49
Hi @Aldugama ,

The idea is to monitor Fortigate firewall logs with **Wazuh** (More info about Log data collection can be found here: https://documentation.wazuh.com/3.10/user-manual/capabilities/log-data-collection/index.html).
So Filebeat is enough to read and send the generated alerts to Elasticsearch, in my opinion Logstash is not needed in your environment. 

I'll explain you how to configure Filebeat to send logs directly to Elasticsearch:
1. As I said in my previous comment, you have to comment the output to Logstash and add the output to Elasticsearch:
```

**Comment by Aldugama** [comment] 2019-11-04 11:57
Ok, now, the filebeat test is working ok once I did as you said in your previous comment.

**Comment by pablotr9** [comment] 2019-11-04 12:14
Hi @Aldugama ,

The idea is to monitor Fortigate firewall logs with **Wazuh** (More info about Log data collection can be found here: https://documentation.wazuh.com/3.10/user-manual/capabilities/log-data-collection/index.html).
So Filebeat is enough to read and send the generated alerts to Elasticsearch, in my opinion Logstash **is not needed** in your environment. 

I'll explain you how to configure Filebeat to send logs directly to Elasticsearch and install Wazuh template:
1. As I said in my previous comment, in your `filebeat.yml` you have to comment the output to Logstash and add the output to Elasticsearch:
```
#output.logstash.hosts: ['localhost:5000'] 
output.elasticsearch.hosts: ['ELASTIC_IP:9200'] # replace ELASTIC_IP with the IP of the Elasticsearch server 
```
2. Restart Filebeat, wait some seconds and check if Wazuh template is installed in Elasticsearch:
```
curl localhost:9200/_template/wazuh
```
The output of that command should show the full template (othewiser something went wrong)

3. Your `wazuh-indices*` indices should have a custom mapping created automatically by Elasticsearch, but they need to have the mapping specified by our template. (This step will remove all the data in your **wazuh-alerts*** indices, if you do not want to lose any data, do not do this step and do a **reindex** instead)
 - Delete `wazuh-alerts*` indices: 
```
curl -XDELETE localhost:9200/wazuh-alerts*
```
Now restart Wazuh manager (this will force the generation of at least one alert and therefore the creation of the wazuh-alerts- index, it can take a few seconds)
```
systemctl restart wazuh-manager
```
Now refresh the field list of the `wazuh-alerts*` index pattern:
![image](https://user-images.githubusercontent.com/35685689/68119900-35424b80-ff04-11e9-9ddc-174636288f02.png)
As shown in that screenshot, go to **Management** -> **Index pattern** -> **wazuh-alerts*** and click on refresh field list.

After following these steps, you should have a new index `wazuh-alerts-3.x-2019-11-04`, now try entering in the Wazuh App and let me know if it works.

Best regards,
Pablo Torres

**Comment by Aldugama** [comment] 2019-11-04 12:21
Ok, thanks, it seems to be working alright. The only thing that's "wrong" is that the agent I've got installed appears as disconnected when it should be active.
For the rest, thank you very much, you really helped me.

Best regards,
Alejandro.

**Comment by pablotr9** [comment] 2019-11-04 12:26
Hi @Aldugama ,

Happy to see it's working correctly, I will close this issue, feel free to open a new issue explaining your issue with the disconnected agent explaining your problem and we will help you there. 

Kind regards,
Pablo Torres

**Closed by pablotr9** 2019-11-04 12:26 UTC
Labels: community, help wanted
