### ISSUE TITLE
Constant Refreshing of Wazuh-Kibana App When Clicked on a particular Agent

### ISSUE THREAD

**Issue by sp31071973** [wazuh/wazuh-kibana-app#2424] opened 2020-08-11 18:22 UTC
| Wazuh | Elastic | Rev |

I am using 3.13 and all recomended version.

**Description**
Short description of your issue.
I have 2 Active Agents. When I clicked on any of the Agents "Open Summary Panel for this Agent" , the Browser Screen Populates for few seconds and immediately starts refreshing. The Refreshing continues in a few seconds span and no meaningful renderation happens.

**Steps to reproduce**

1. Setup Wazuh 3.13 as per recomendation
2. Add at least 1 agent, should be active 
3. In the list from Wazuh Kibana App, search the Agent, click on the eye icon

The resulting screen constantly refresh.

**Screenshots**
![image](https://user-images.githubusercontent.com/4557813/89933653-02fd1180-dc2d-11ea-82ca-e40dce25645f.png)

**Additional context**
On the Flickering Screen (Browser) , I pressed F12 and could see some error.

TypeError: Cannot read property 'length' of undefined
    at RequirementsBody (wazuh.bundle.js:57)
    at ua (kbn-ui-shared-deps.js:342)
    at Ya (kbn-ui-shared-deps.js:342)
    at xs (kbn-ui-shared-deps.js:342)
    at ml (kbn-ui-shared-deps.js:342)
    at hl (kbn-ui-shared-deps.js:342)
    at ol (kbn-ui-shared-deps.js:342)
    at kbn-ui-shared-deps.js:342
    at t.unstable_runWithPriority (kbn-ui-shared-deps.js:350)
    at Hi (kbn-ui-shared-deps.js:342)

**Comment by jsanchez91** [comment] 2020-08-12 06:50
Hi @sp31071973,

Other user report the same error in this issue: https://github.com/wazuh/wazuh-kibana-app/issues/2376

The user's problem was because his Elasticsearch had no wazuh index, could you check if you have any wazuh index?

Run this command in the Kibana dev_tools to check this:
```
GET _cat/indices
```
![dev_tools](https://user-images.githubusercontent.com/3064506/87670323-d3630280-c76f-11ea-93f8-39e50f003b20.gif)

Let me know the result

**Comment by sp31071973** [comment] 2020-08-12 09:40
I ran it. Response goes as below

```
green  open .apm-custom-link                 0811-AacT2G8oPyh9byrOw 1 0   0 0    208b    208b
green  open .kibana_task_manager_1           w-6MAc0OSUW47RzQYuxgmQ 1 0   5 3  40.5kb  40.5kb
green  open wazuh-monitoring-3.x-2020.08.11  DQwPiy7rQgidnA_J8uafwA 2 0  82 0 197.9kb 197.9kb
green  open .apm-agent-configuration         SWOwfdIDS52SYgNvIlA9RA 1 0   0 0    208b    208b
yellow open filebeat-7.8.1-2020.08.06-000001 GtHUt9QLScWUp8Jd64bslA 1 1   0 0    208b    208b
green  open wazuh-monitoring-3.x-2020.08.12  DRhUuLD_TlqAxwACRnj39g 2 0  78 0 131.9kb 131.9kb
green  open .kibana_2                        22b1nXmCQTeIVhV_RgNcVg 1 0 185 1 134.8kb 134.8kb
green  open .kibana-event-log-7.8.1-000001   0q2QLufwS42CkBMNI5FFaQ 1 0   8 0  30.9kb  30.9kb
green  open .kibana_1                        v97z3kfEQ_WDoA9-0pcqLA 1 0  10 2  65.3kb  65.3kb
green  open wazuh-monitoring-3.x-2020.08.06  R-4NzZO1R-uhbIUE40mGbQ 2 0   0 0    416b    416b

```

**Comment by jsanchez91** [comment] 2020-08-12 11:12
Yes, your Elasticsearch doesn't have any wazuh-alert, you probably have some problem in the Filebeat configuration. Follow these steps to check it out:

1. Check if the wazuh module exists:
List the items in the filebeat/module folder and look for the wazuh directory:
```bash
ls /usr/share/filebeat/module/
```

![image](https://user-images.githubusercontent.com/3064506/88026603-66b48300-cb36-11ea-9e15-d9016536ce7e.png)

If you did not find the Wazuh module use the following command to download it
```bash
curl -s https://packages.wazuh.com/3.x/filebeat/wazuh-filebeat-0.1.tar.gz | sudo tar -xvz -C /usr/share/filebeat/module
```

2. Download the Filebeat configuration file for wazuh
```bash
curl -so /etc/filebeat/filebeat.yml https://raw.githubusercontent.com/wazuh/wazuh/v3.13.1/extensions/filebeat/7.x/filebeat.yml
chmod go+r /etc/filebeat/filebeat.yml
```

Open the file `/etc/filebeat/filebeat.yml` with your favorite editor and replace the elasticsearch IP value for the IP of your elasticsearch server.
```bash
# Open the file
vi /etc/filebeat/filebeat.yml

# Go to the last line and edit the value of `output.elasticsearch.hosts`
output.elasticsearch.hosts: ['http://<YOUR_ELASTIC_SERVER_IP>:9200']
```

Then save the file and test your configuration:
```bash
filebeat test output
```

3. Download the Wazuh-template:
```bash
curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.13.1/extensions/elasticsearch/7.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json
```

4. Restart Filebeat to apply the changes
```bash
systemctl restart filebeat.service
```

After these changes go to Kibana and check if the Wazuh index has been created running again the command `GET _cat/indices` in the Kibana dev_tools

**Comment by sp31071973** [comment] 2020-08-14 07:52
Thanks a lot, it solves. Apparently, I missed 1/2 steps that caused havoc. You please close the issue and may be linked to 2376. Had it been cleared to me that it is the same issue, I would not have logged the bug.

**Comment by juankaromo** [comment] 2020-08-20 15:33
I'm closing the issue because apparently it's resolved. Related #2376

**Comment by 0xtaf** [comment] 2020-09-18 09:45
green open .kibana-event-log-7.8.0-000001  s01ucz1SSMWNNPCTizRD1Q 1 0   3  0  15.5kb  15.5kb
green open .apm-custom-link                br1kBZjgQb6dypsEPvIUOw 1 0   0  0    208b    208b
green open .kibana_task_manager_1          iw_jrcELQkWOHMfBGbGqlA 1 0   5 10    11kb    11kb
green open .apm-agent-configuration        rbkWtvIsTeSy5HqvNuWZOg 1 0   0  0    208b    208b
green open .kibana_2                       -K4YfOJkSn6SAWF0LPncEQ 1 0  48  8 181.4kb 181.4kb
green open wazuh-alerts-3.x-2020.09.18     ciVmbH35Tauavv4hgaHzQw 3 0 606  0   1.2mb   1.2mb
green open wazuh-alerts-3.x-2020.07.14     9nOhOVZkSq2qp_Fvjyfjhg 3 0  33  0 142.5kb 142.5kb
green open .kibana_1                       a1LMgDOtRpqOWhvEYHN6bw 1 0   7  3  67.9kb  67.9kb
green open wazuh-monitoring-3.x-2020.09.18 mXmLX5ljRIucj4FvTM04yA 2 0   8  0 131.1kb 131.1kb

my elasticsearch has wazuh alerts but I'm still having the blank page problem. can you please help?

**Comment by jsanchez91** [comment] 2020-09-22 11:48
Hi @0xtaf,

Sorry for the late response,

Your problem may be caused by this other error:
https://github.com/wazuh/wazuh-kibana-app/issues/2396#issuecomment-663576267

If the problem persists, you could share with me if you have any error in the browser console (Press F12 to see it).
![image](https://user-images.githubusercontent.com/3064506/93878326-2ca06280-fcda-11ea-902a-c70e2a039259.png)

**Comment by 0xtaf** [comment] 2020-09-22 11:52
Hi @jsanchez91,

No problem and thank you for the reply. It was kind of urgent for me to solve the problem at that time so the stable branch worked for me and I haven't tried after that tbh. If I happen to encounter such a problem again, I'll definitely inform you with the screenshots.

**Comment by jsanchez91** [comment] 2020-09-28 07:17
We would appreciate any information if you try to reproduce the error again.
We will close the Issue again, but feel free to add a comment if you need to.

**Closed by jsanchez91** 2020-09-28 07:17 UTC
Labels: bug, community

**Comment by F-Masood** [comment] 2021-05-18 18:30
hi, 
Iam having same issue. 

`My OS is: Ubuntu 20.04 LTS`
```

command: cat /usr/share/kibana/package.json | grep version
output: "version": "7.10.2"
```

```
command: cat /var/ossec/etc/ossec-init.conf | grep VERSION
output: VERSION="v4.1.5"
```

filebeat is running properly, but the same **problem of refreshing** is happening, any nudge on this, please ?

**Comment by F-Masood** [comment] 2021-05-18 18:38
my bad, the issue is coming on **Firefox** but not on **Chrome**, this is `strange` :-/

**Comment by frankeros** [comment] 2021-05-18 19:08
Hi @F-Masood, it sounds like a cache issue. Please try it in Firefox but in private mode. If the error is not, you should clear the cache on Firefox (normal mode) following these [steps](https://documentation.wazuh.com/current/user-manual/kibana-app/troubleshooting.html#wazuh-kibana-plugin-page-goes-blank) 
Bests
