### ISSUE TITLE
App tabs empty

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh-kibana-app#34] opened 2017-10-09 10:01 UTC
Using ELK 5.6.2 and Wazuh 2.1.1 i'm seeing blank overview and agent tabs for all sections - overview, file integrity, policy monitoring, scap, audit, and PCI DSS. The data is coming in - individual Kibana dashboards for these aspects work, and the indices are populating. Something is amiss with the wazuh-kibana app itself (it does show agents registering and all that jazz, so its definitely talking to the Wazuh API).
Am i doing something wrong here? App installed as per instructions in the docs via the kibana-plugin install targeting the 2.1.1 zip.

**Comment by havidarou** [comment] 2017-10-09 18:38
Hello,

sorry you are having problems.

What do you mean by blank tabs, could you share a screenshot?

You can see if the API credentials are properly stored by doing: 

```curl -XGET elasticsearch_host:9200/.wazuh/_search?pretty```

If you followed the installation guide everything should be ok.

Regards.

**Comment by sempervictus** [comment] 2017-10-09 23:39
@havidarou: [this is what all the tabs for overview and individual agents look like](https://pasteboard.co/GOcrpFl.png).
The API credentials are correct, or i wouldn't have agent status updates and information. Repeated deploys are showing this, happens with direct TCP socket to kibana or via nginx TLS proxy.
Platform is Ubuntu 14.04

**Comment by havidarou** [comment] 2017-10-10 00:53
@sempervictus we can try to trace where the problem is.

First, if you click the Discover in Kibana and do a search in that time interval, do you see alerts?

If not, Kibana is not able to reach Elasticsearch.

On the other hand, we can check if Elasticsearch is getting alerts by:

```curl -XGET elasticsearch_host:9200/wazuh-alerts-date_in_interval/_search?pretty```

If you don't see alerts in Elasticsearch, then the problem is happening prior that point.

Let me know what you get and we can continue debugging.

Regards.

**Comment by sempervictus** [comment] 2017-10-10 01:05
Alerts work, dashboards work too. Api auth and elk work, its localized to the app in kibana apparently.

**Comment by havidarou** [comment] 2017-10-10 01:15
@sempervictus can you paste your Wazuh app package.json file?

**Comment by sempervictus** [comment] 2017-10-10 10:02
Sure, thanks for tracking this down:
```
{
  "name": "wazuh",
  "version": "2.1.1",
  "revision": "0345",
  "kibana": {
    "version": "5.6.2"
  },
  "description": "Wazuh App",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
  "agents": {
	"add": true,
	"delete": true,
	"restart": true
  },
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "dependencies": {
    "angular-animate": "1.4.7",
    "angular-aria": "1.4.7",
    "angular-cookies": "1.4.7",
    "angular-material": "1.1.1",
    "angular-md5": "^0.1.10",
    "bootstrap": "3.3.6",
    "install": "^0.10.1",
    "needle": "^1.0.0",
    "node-cron": "^1.1.2",
    "npm": "^5.3.0"
  }
}
```

**Comment by havidarou** [comment] 2017-10-10 22:36
@sempervictus Everything seems correct...

You can try to reinstall the app.

First, remove the .wazuh index:

```curl -XDELETE elastic_host:9200/.wazuh```

Then the .kibana one (careful here, you are deleting the Kibana configuration, visualizations, etc):

```curl -XDELETE elastic_host:9200/.kibana```

Now remove the Wazuh app:

```/usr/share/kibana/bin/kibana-plugin remove wazuh```

And then reinstall it:

```/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.2.zip```

**Comment by sempervictus** [comment] 2017-10-10 22:57
Thanks, tried that a few times with no luck.
Kibana installed from the tar.gz they provide, host OS is Ubuntu 14.
No difference behind nginx or not.

**Comment by havidarou** [comment] 2017-10-12 06:18
@sempervictus was it working at some point or was faulty from the start?

The OS shouldn't be a problem, specially if Kibana itself is working.

**Comment by sempervictus** [comment] 2017-10-12 08:11
Never seen it work, but I'm a recent convert to the system, started on 2.1.1

**Comment by havidarou** [comment] 2017-10-13 08:04
@sempervictus Just to recap, the discover tab inside Kibana shows Wazuh alerts. This is important because it means the data flow has reached Kibana and, therefore, the problem is in the app.

If that's the case, can you please show me the browser's console and network log when you load the Wazuh app?

Regards.

**Comment by JuanjiJG** [comment] 2017-12-04 15:57
It's been more than a month since the last response to this issue, so we proceed to close it.

Regards.

**Comment by sempervictus** [comment] 2017-12-11 19:06
Apologies, didnt notice the request rom @havidarou, but its still an issue, on every deployment we've done, with every browser used to access the Kibana app (we think its in the app itself).

Below are images of a network and console view for the agent pane of the manager itself - the very first agent to be deployed, and they all look like this:

![wazuh_agent_network](https://user-images.githubusercontent.com/1331084/33848705-871127e2-de7c-11e7-9a0c-7e6d074823a0.png)
![wazuh_agent_console](https://user-images.githubusercontent.com/1331084/33848706-87215fea-de7c-11e7-8a5c-85b60b385ad3.png)


Thanks for looking into this

**Comment by havidarou** [comment] 2017-12-14 18:02
Hi @sempervictus 

we just released our version 3.0.0, which, as date of today, goes along Elastic Stack 6.1.0.

Everything has been improved, you could give it a try.

Regards.

**Comment by sempervictus** [comment] 2017-12-29 18:40
@havidarou: we actually can't do that - ES6 breaks a ton of other things, and clients usually log multiple data streams into their ELK clusters - OSSEC doesn't generate enough data to warrant the resource investment of a cluster stack on its own for many folks. Unfortunately while 3.0 seems very cool, we cant push to production until the rest of the world catches up a bit and there's a sane migration path from 5->6 for production systems

**Comment by JuanjiJG** [comment] 2017-12-29 19:18
Hi @sempervictus,

Since you cannot upgrade to the newer Elastic Stack 6, we'll try to figure out what's going on on your current installation. As my coworker Javier told you, it's important to verify if the data flow from the manager to Kibana is working fine.

1. Let's try something. First, go to the **Discover** tab, available on the upper left side of the window (underneath the Kibana logo). There must be alerts on that tab. You can check the **Hits** counter on the upper right corner of the screen. If the counter is at `0`, ensure you've selected an appropriate time range (for example, 1 week or 1 month, but you can also try with `Last 24 hours`).
![hits](https://user-images.githubusercontent.com/10928321/34445585-012ada94-ecd5-11e7-8798-12147fcfa1ff.PNG)
Tell me the results from that tab. You can take a screenshot of that so we can better check the problem.

2. Then, go to a terminal console on the machine that has installed **Elasticsearch** and put the following command:
`curl -XGET localhost:9200/_cat/indices?v`

Take a screenshot of the output and post it on a comment. After you send me the results, we'll carry out an investigation to see what may be the cause.

Thank you for your patience, I hope we can find a solution for your problem.

Best regards,
Juanjo

**Comment by jesusgn90** [comment] 2018-01-29 08:16
Hi @sempervictus it's been a month since the last response from our team, so I'm going to close this issue, if you are facing any more trouble feel free to create a new issue.

Best regards,
Jesús

**Closed by jesusgn90** 2018-01-29 08:16 UTC

**Comment by sempervictus** [comment] 2018-01-29 08:44
We have been moving to v3, though some places are still and will be on 2 for a while (had to monkeypatch the rule updater to fail early for now). Compared to the enforced feed change, this is negligible :-).
