### ISSUE TITLE
deleted file not display at dashboard

### ISSUE THREAD

**Issue by prashantvidja** [wazuh/wazuh-kibana-app#501] opened 2018-05-26 10:38 UTC
Hello

I have installed wazuh-kibana-app and agent install in my windows pc.
and set my folder at syscheck block in ossec.conf with below syntax.

**<directories report_changes="yes" check_all="yes" realtime="yes"\>C:\test_fim2</directories\>**

at dashboard only new added file and changed file displays when i delete file from my system it is not display.
I attached my dashboard photos below
![screenshot](https://user-images.githubusercontent.com/26060662/40575276-bccb39b2-60ff-11e8-8fd0-634ffcf65568.png)

Thanks

**Comment by gagantous** [comment] 2018-05-26 14:09
I believe there is a typo on your syntax... 
Its should be </directories>

**Comment by prashantvidja** [comment] 2018-05-26 14:11
Syntax in ossec.conf file??
Which file configuration?
Thanks

**Comment by gagantous** [comment] 2018-05-27 06:45
@prashantvidja 

It your conf you wrote

`<directories report_changes="yes" check_all="yes" realtime="yes">C:\test_fim2/directories>`

That should be

`<directories report_changes="yes" check_all="yes" realtime="yes">C:\test_fim2</directories>`

**Comment by prashantvidja** [comment] 2018-05-27 06:59
@gagantous

Sorry,This was my writing mistake in my ossec.conf synatx is right.
also if there is syntax error then "changes in file", "added file" alert also not display at dashboard.
But in my condition only when i delete file, it 
not displayed.
And also i check alert.json file in wazuh manager i did not find any "deleted file" log but i found file "changes file" ,"added file log"
So agent not sending deleted file log to manager.
But still i did not get any solution help me.

Thanks for your precious replay

**Comment by havidarou** [comment] 2018-05-27 10:14
Hi @prashantvidja ,

I have tested it with a Windows agent and it is working fine.

You can search in your alerts.json (this is where the manager stores the alerts) for the specific alert regarding the file deletion.

That file is located in ```/var/ossec/logs/alerts/alerts.json```

The specific rule id regarding this event is 553 and the full_log field for that event should look something like:

```File 'C:\my_file_path' was deleted. Unable to retrieve checksum.```

Let me know if that helps you.

Regards.

**Comment by prashantvidja** [comment] 2018-05-28 04:57
@havidarou sorry for let reply,

i check logs but i did not did not find anything like  
"File 'C:\test_fim2\my_file_name' was deleted. Unable to retrieve checksum."
and also i did not find single word "deleted"  in log.
and i check rule 553 it is available in 0015-ossec_rules.xml file.
so rule is also ok then where is the issue? 

Thanks

**Comment by havidarou** [comment] 2018-05-28 12:42
Hi @prashantvidja ,

the rules and decoders are stored in the manager, not in the agents.

It seems the rule for the file deletion hasn't been triggered.

Regarding the alert for the file deletion, keep in mind file deletion alerts are only generated if you use syscheck in realtime.

Realtime is active after rootcheck and syscheck default scans have finished, so if you start the manager and then delete the file without realtime being active you won't see the alert.

You can check ```/var/ossec/logs/ossec.log``` to see when realtime is active in the manager.

Hope that helps.

Regards.

**Comment by prashantvidja** [comment] 2018-05-29 05:35
hello @havidarou 

I think that was not issue because i am doing" file change" and "delete file" both operation together but i got only "file change" alert.
And one more query,
for checking this first i change file but i did not get any alert after i restart wazuh-agent then I got alert instantly. so why it required restart wazuh-agent? 

Thanks a lot

**Comment by havidarou** [comment] 2018-05-29 09:09
Hi @prashantvidja ,

as I mentioned, when you start the manager you need to wait for the syscheck scan to complete and then realtime analysis will start.

That is why you don't get the deletion alert, because those kind of alerts are only available on realtime and it hasn't started yet.

Regarding your query I would say it's caused by the same reason: the manager hasn't been able to complete its syscheck scan yet.

Hope that helps.

Regards.

**Comment by prashantvidja** [comment] 2018-05-31 13:07
hello @havidarou 

i have still same issue,
i paste my log of  manager

2018/05/31 13:44:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/syslog'.
2018/05/31 13:44:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2018/05/31 13:44:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/kern.log'.
2018/05/31 13:44:11 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2018/05/31 13:44:11 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2018/05/31 13:44:11 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2018/05/31 13:44:11 ossec-logcollector: INFO: Started (pid: 27713).
2018/05/31 13:44:41 ossec-syscheckd: INFO: Syscheck scan frequency: 60 seconds
2018/05/31 13:45:11 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2018/05/31 13:45:11 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/05/31 13:50:37 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2018/05/31 13:50:47 ossec-syscheckd: INFO: Ending syscheck scan (forwarding database).
2018/05/31 13:51:07 rootcheck: INFO: Starting rootcheck scan.
2018/05/31 13:51:34 rootcheck: INFO: Ending rootcheck scan.
2018/05/31 13:56:34 ossec-syscheckd: INFO: Starting syscheck scan.
2018/05/31 14:02:31 ossec-syscheckd: INFO: Ending syscheck scan.


In that i  see syscheck complete successfully but it take time.
is this issue?
Thanks

**Comment by havidarou** [comment] 2018-06-03 09:38
Hi @prashantvidja,

sorry for the late response.

Those are the standard syscheck scan log messages.

After that you should see something like:

```2018/06/01 15:31:21 ossec-syscheckd: INFO: Initializing real time file monitoring engine.```
```2018/06/01 15:31:21 ossec-syscheckd: INFO: Real time file monitoring engine started.```

That means realtime scanning is active and, from that moment on, you should get deletion alerts.

Hope that helps.

Regards.

**Comment by jesusgn90** [comment] 2018-06-20 14:08
Hello @prashantvidja , Is your problem solved? Please let us know, this way we can help you if the problem still persists or close the issue if it's now solved. Thanks in advance.

Regards,
Jesús

**Closed** 2018-06-25 10:50 UTC
Labels: [release] 3.3, [wazuh] core, help wanted

**Comment by 1xcalibur1** [comment] 2018-11-13 09:32
Hi,

I'm experiencing the same issue as above only in my case, it's as if almost nothing happens.
I'm not getting any deletion of modification messages at all. Only creation notifications and those also come in very late.

Here's the line I have in the agent config file:

<directories report_changes="yes" check_all="yes" realtime="yes">C:\wazuhtest</directories>

I am only seeing the following in the fashboard:
![image](https://user-images.githubusercontent.com/20181696/48403860-8d9e9d00-e737-11e8-84de-eeeb9994dacc.png)

I'm running Elastic 6.2.4 and Wazuh 3.2.1.

Appreciate the help!
Thanks
X

**Comment by jesusgn90** [comment] 2018-11-13 09:51
Hi @1xcalibur1 ,

Since Wazuh 3.2.1, we have known issues regarding syscheck at your versions, also we have improved a lot those alerts and Wazuh syscheck system. You may be facing a bug. 

Is it a problem for you to upgrade to our latest release? 

- Elastic 6.4.3
- Wazuh 3.7.0

If you still need to be freeze at those versions I can try to reproduce your error more in deep.

Regards,
Jesús

**Comment by 1xcalibur1** [comment] 2018-11-13 12:35
That actually worked remarkably well!

While we're at it, may I ask how can I setup an alert for specifically just the deleted files?

Thanks a lot!

**Comment by jesusgn90** [comment] 2018-11-13 13:42
Hi @1xcalibur1 ,

I'm glad you got it solved just upgrading. Regarding your question, I want to say they already have specific alerts, take a look:

![image](https://user-images.githubusercontent.com/8860227/48416796-694fba00-e751-11e8-9fd8-caca45175080.png)

The main difference is the `syscheck.event` type. In the above picture you can see three alerts for a testing file.

Here is my `syscheck` block in the `ossec.conf` file:

```xml
<syscheck>
  ...
  <directories check_all="yes" whodata="yes">/home/vagrant/test</directories>
  ...
</syscheck>
```

First of all I've installed `audit` in order to enrich even more my alerts using the recently added `whodata` features, then I've executed the next commands for generating those three alerts:

```
[root@single-host filebeat]# mkdir /home/vagrant/test
[root@single-host filebeat]# touch /home/vagrant/test/foo.txt  
[root@single-host filebeat]# echo "Hello world" >> /home/vagrant/test/foo.txt 
[root@single-host filebeat]# rm -rf /home/vagrant/test/foo.txt 
```

Useful links:

- [Whodata - Windows](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows.html?highlight=whodata#auditing-who-data-in-windows)
- [Whodata - Linux](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html?highlight=whodata)
- [FIM - How it works](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/how-it-works.html)
- [Rule 550](https://github.com/wazuh/wazuh-ruleset/blob/cb18f3fd070c33e5923fc74dafb6ea84ada69143/rules/0015-ossec_rules.xml#L194)

I hope it helps.

Kind regards,
Jesús

**Comment by 1xcalibur1** [comment] 2018-11-13 14:04
Well, that's almost what I meant :)
The data is being fed to Wazuh just fine and I can easily locate it.
My question is, what's the mechanism to trigger an email alert once syscheck.event has meat the "delete" condition? I could script a query with Python but there ought to be something builtin for that, right?

Thanks again,
X

**Comment by jesusgn90** [comment] 2018-11-13 15:30
Hi @1xcalibur1 ,

We have custom rules (Eg: [syscheck deleted](https://github.com/wazuh/wazuh-ruleset/blob/af57107c0e77c56c49e65b87e198931a5719e921/rules/0015-ossec_rules.xml#L201)) for each syscheck event, for now we have a known bug and it's always triggering the rule 550 as you can see in my last comment.

### Goal

Have alerts by e-mail when `syscheck.event` is `deleted`.

### Solution

Our `mail` integration is able to filter by `rule.id` so we need a custom `rule.id` for filtering our syscheck deletion alerts.

Creating the custom rule:

- Edit `/var/ossec/etc/rules/local_rules.xml`

Edit the existing one example rule:

```xml
<group name="local,syslog,sshd,">

  <rule id="100001" level="8">
    <match>deleted</match>
    <category>ossec</category>
    <decoded_as>syscheck_integrity_changed</decoded_as>
    <description>RULE WORKING.</description>
    <group>syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,</group>
  </rule>

</group>
```

Once edited, save it and restart the Wazuh manager.

#### Verify your new rule

```
[root@single-host filebeat]# systemctl restart wazuh-manager
// Wait some seconds
[root@single-host filebeat]# touch /home/vagrant/test/foo-3.txt
[root@single-host filebeat]# echo "Hello world" >> /home/vagrant/test/foo-3.txt 
[root@single-host filebeat]# rm /home/vagrant/test/foo-3.txt 
```

Now you can check that our alert has its new `rule.id`:

![image](https://user-images.githubusercontent.com/8860227/48422779-a7ec7100-e75f-11e8-8cc6-bd010a09ed29.png)

### Configure your e-mail integration

Just follow our guide located at: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html

Our `rule.id` is 100001, let's configure it following this useful article: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?highlight=mail#email-based-on-rules-id

Something like this:

```xml
<email_alerts>
  <email_to>you@example.com</email_to>
  <rule_id>100001</rule_id>
  <do_not_delay />
</email_alerts>
```

### Related tickets

Stay updated tracking these tickets:

- https://github.com/wazuh/wazuh/issues/1875
- https://github.com/wazuh/wazuh/issues/1852

Sorry about the incoveniences, we'll try to fix it as soon as possible.

Kind regards,
Jesús

**Comment by npstnoida** [comment] 2020-12-31 07:29
when i am  create directories and then delete so its not  show in dashboard 
 root@ubuntu:~/demo# mkdir mount-dir
root@ubuntu:~/demo# rm -rf mount-dir

In Integrity monitoring not monitoring  directory its only monitoring file why??

please help me

**Comment by npstnoida** [comment] 2020-12-31 07:30
when i am create directories and then delete so its not show in dashboard
root@:/demo# mkdir mount-dir
root@:/demo# rm -rf mount-dir

In Integrity monitoring not monitoring directory its only monitoring file why??

please help me
