### ISSUE TITLE
Agent tab running into "Something went wrong." error

### ISSUE THREAD

**Issue by Cyber-MKO** [wazuh/wazuh-kibana-app#4289] opened 2022-06-24 18:32 UTC
| Wazuh | 
| ----- |
| 4.3.3 |

| Browser |
| ------- |
| Chrome|

**Description**
I keep getting this error with "Something went wrong." with details stating "ReferenceError: ResizeObserver is not defined" as shown in the screenshot attached. This happens when I click on the agent tab.

**Wazuh Component information:**

- Wazuh dashboard version (4.3.4) 
- Wazuh manager version (4.3.4)

**Wazuh Agents information:** 
- 001 --> windows10 (wazuh agent version 4.3.3)
- 002 --> windows11 (wazuh agent version 4.3.4)

 **Details that appear in the error**
  ReferenceError: ResizeObserver is not defined

**Errors in the console tab:**
```
ReferenceError: "ResizeObserver is not defined"
    useChartDimensions https://localhost/1/bundles/plugin/wazuh/wazuh.chunk.9.js:5
    ps https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    El https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    unstable_runWithPriority https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:442
    Hi https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    Sl https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    ol https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    Gi https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    unstable_runWithPriority https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:442
    Hi https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    Gi https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    Vi https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    sl https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    Gl https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    render https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434
    renderComponent https://localhost/1/bundles/plugin/wazuh/wazuh.chunk.5.js:24
    $digest https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:426
    $apply https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:426
    r https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:426
    completeTask https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:426
    r https://localhost/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:426
osd-ui-shared-deps.js:434:77072
```
 
**Screenshots**
![image](https://user-images.githubusercontent.com/56613782/175631998-0422ce0b-6cdb-4e47-be42-0086263be377.png)

**Comment by Desvelao** [comment] 2022-06-27 11:05
Hi @Cyber-MKO , 

What browser and version of this are you using?

I think the problem is related to the `ResizeObserver` is not supported by your browser or browser/version. You can review if it is supported here: https://caniuse.com/resizeobserver

**Comment by Cyber-MKO** [comment] 2022-06-30 13:00
Hello Team,

It is indeed working now after the upgrade. you can close this.

**Comment by Desvelao** [comment] 2022-07-01 06:05
Thank you so much for confirming the solution to the problem.

I will close this issue.

**Closed by Desvelao** 2022-07-01 06:05 UTC
Labels: bug, operations
